### ISSUE TITLE
js: odata-v2: deserializeEntity not available, but documented

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk#1083]
Hi SAP,

I am on my way finding a solution to use a json to create a EntityBuilder.
I will open an issue on the js-equivalent repository. Nevertheless, I tried to use `deserializeEntity`, described [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#deserialize-an-odata-json-response-to-an-entity) and discovered it's not available.

Please adjust the documentation accordingly. 

Thanks :) 

Kind regards,
Cedric

**Comment by FrankEssenberger** [comment]
Hi @drvup,

thanks for pointing this out. I guess the documentation is outdated. Try to create the deserialize method like:

```
entityDeserializer(defaultDeSerializers).deserializeEntity(rawObject)
```

Best
Frank
