### ISSUE TITLE
JSON Web Token Bearer Token Grant with client secret in body of request

### ISSUE THREAD

**Issue by paniman** [SAP/cloud-sdk#1107]
Hi,
I have a question regarding requesting a JWT.

Normally we would send a POST request to e.g.:
https://url.to/oauth/token?client_id=MYSECRETCLIENTID&client_secret=MYSECRETCLIENTSECRET&grant_type=client_credentials

When we set the java log level to a very low level, we would write the client id and client secret in our logs (because the client secret is included in the request URL)

The documentation says, that we need to set the Content-Type to "Content-Type: application/x-www-form-urlencoded".
Is there another way to send the client secret in the body instead of the uri?

Best regards,
Steve

**Comment by newtork** [comment]
Hi Steve,

* If an attacker has access to log view and level controls, then they can monitor all traffic. Whether the secret is part of HTTP URL query or HTTP body entity, this wouldn't make a difference technically.

* When using content-type `application/x-www-form-urlencoded` then the HTTP URL query will be moved **automatically** to HTTP body.
  ```diff
  - POST https://url.to/oauth/token?client_id=MYSECRETCLIENTID&client_secret=MYSECRETCLIENTSECRET&grant_type=client_credentials
  

  + POST /oauth/token HTTP/1.1
  + HOST url.to
  + Content-Type: application/x-www-form-urlencoded
  + 
  + client_id=MYSECRETCLIENTID&client_secret=MYSECRETCLIENTSECRET&grant_type=client_credentials
  ```


> Is there another way to send the client secret in the body instead of the uri?

* AFAIK on the network layer it's always represented in the body, never the URI.

**Comment by paniman** [comment]
Hi Alexander,
you are right! Thank you for your time and explanation!
The logging format was misleading me, because it looked like the parameters were added to the URL instead of the body, but that's really not the case.

Best regards,
Steve
