### ISSUE TITLE
Cloud SDK Issue

### ISSUE THREAD

**Issue by skvallabhaneni** [SAP/cloud-sdk#1108]
I am referring to the documentation of 'Getting Started SAP Cloud SDK' page. The page gives lot of required information which is very helpful to start with. But looks like the link given in 'More Step-by-Step Guides' is not working. It is taking to a page where it displays 'No Tutorials Found'.

The page which I am referring here is https://sap.github.io/cloud-sdk/docs/java/getting-started

Can you please take a look.

**Comment by newtork** [comment]
Thank you for hinting on the broken link 👍 

I created a PR to address the issue: https://github.com/SAP/cloud-sdk/pull/1109

**Comment by Johannes-Schneider** [comment]
The link has been fixed.
Thanks once again for reporting this issue, @skvallabhaneni!
