### ISSUE TITLE
Memory leak from eventing

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [SAP/cloud-sdk#1168]
We're observing memory problems with the QPID JMS eventing that comes with the Cloud SDK. Please refer to https://stackoverflow.com/questions/74733418/what-reserves-and-holds-my-java-memory-when-sending-out-amqp-events-from-my-spri for a more detailed description.

Our application runs a process, then sends out some hundreds to thousands of events. While this works, we afterwards see that the application holds on to large memory areas for several hours. Further load within that time will cause the app to run out of memory and crash. We also observe an increase of memory consumption over time, without further load. First memory analysis suggests a memory leak, probably in some lower dependency like Netty.

(A quick look into mvn dependency:tree also showed some old and unreliable version numbers, e.g. the "alpha-2" in `org.apache.geronimo.specs:geronimo-jms_2.0_spec:jar:1.0-alpha-2` does not sound like a stable release and is one year behind their current release 2.x.)

Could we please get in touch to discuss the issue and find out whether it's related to the CloudSDK or its dependencies?

**Comment by cschubertcs** [comment]
Hi @HrFlorianHoffmann,

thanks for reaching out to us!
Can you please provide the dependency tree, so that we can see which version and modules of the SDK you are using?

**Comment by HrFlorianHoffmann** [comment]
[dependency-tree.txt](https://github.com/SAP/cloud-sdk/files/10194748/dependency-tree.txt)

**Comment by cschubertcs** [comment]
Thanks for the swift reply!

The messaging related functionality that you use seems to come from the Cloud Application Platform (CAP) related modules, specifically `com.sap.cloud.servicesdk.xbem:emjapi-extension-sap-cp-jms`.
This support channel here is focused on the SAP Cloud SDK (modules with a group id starting with `com.sap.cloud.sdk.`), so I cannot help you directly with the memory leak.

If my search pointed me correctly, this should the documentation of CAP related to messaging: https://cap.cloud.sap/docs/java/messaging-foundation
In there you can find in the top right a link to the [SAP answers](https://answers.sap.com/questions/ask.html?primaryTagId=9f13aee1-834c-4105-8e43-ee442775e5ce&b=%3Cp%3E%3Cb%3EI%20am%20referring%20to%20URL:%3C/b%3E%3Cp%3Ehttps%3A%2F%2Fcap.cloud.sap%2Fdocs%2Fjava%2Fmessaging-foundation%3C/p%3E%3Cp%3E%3Cb%3EPlease%20get%20back%20to%20me%20on%20the%20following%20feedback:%3C/b%3E%3C/p%3E) page, where you can ask the CAP colleagues directly.

As we cannot help you further here in this repo, I will close this issue.
Let me know if you have any concerns or objections by re-opening the issue.

Greetings
Chris
