### ISSUE TITLE
WebSecurityConfigurerAdapter is deprecated in Spring Security 5.7.0-M2

### ISSUE THREAD

**Issue by JerryZhang0929** [SAP/cloud-sdk#1182]
As WebSecurityConfigurerAdapter is deprecated, could you please update the sample code in SecurityConfiguartion.java to use  SecurityFilterChain instead.  The cloud security provides some sample code in GitHub.
[Spring Security without the WebSecurityConfigurerAdapter](https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter)
[Sample code](https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java)

I know the sample code is commented out and is only an example in cloud sdk for Java project template. It would be better for us to have the latest sample code and use it directly.

**Comment by KavithaSiva** [comment]
Hi @JerryZhang0929 ,

Thanks for reaching out to us. I have created an internal pull request to update our archetype with the necessary changes.
I will let you know when it gets merged and released.
We refer to the XSUAA library's samples to update our SecurityConfiguration, so you can also refer to their [configuration file](https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java) to know about the actual changes in the meanwhile.

Regards,
Kavitha

**Comment by KavithaSiva** [comment]
Hi @JerryZhang0929, 

Apologies, I missed updating the issue earlier. The updates have been shipped two months back and are available in all subsequent versions starting from `4.6.0` of SAP Cloud SDK.

Regards,
Kavitha
