### ISSUE TITLE
No ThreadContext available for thread 

### ISSUE THREAD

**Issue by RuchiDhiman** [SAP/cloud-sdk#119]
## Issue Description

Hi Colleagues,

I am trying to pass request attributes and security context to an asynchronous thread. I call method AuthTokenAccessor.getCurrentToken(), before the async thread starts, to access the AuthToken. Here I get the exception saying no ThreadContext available (See below). It is unclear to me how to use RequestFilter to set the ThreadContext. (There are no examples in the documentation). Please help in resolving the below exception. Here is the source code that is part of my pull request: https://github.wdf.sap.corp/GRC-CH/AutomatedProcedures/pull/2910

Greetings,
Ruchi

> 
> com.sap.cloud.sdk.cloudplatform.thread.exception.ThreadContextAccessException: No ThreadContext available for thread id=29.
> 	at com.sap.cloud.sdk.cloudplatform.thread.ThreadLocalThreadContextFacade.lambda$tryGetCurrentContext$0(ThreadLocalThreadContextFacade.java:45)
> 	at io.vavr.control.Try.flatMapTry(Try.java:490)
> 	at io.vavr.control.Try.flatMap(Try.java:472)
> 	at com.sap.cloud.sdk.cloudplatform.thread.ThreadLocalThreadContextFacade.tryGetCurrentContext(ThreadLocalThreadContextFacade.java:38)
> 	at io.vavr.control.Try.flatMapTry(Try.java:490)
> 	at io.vavr.control.Try.flatMap(Try.java:472)
> 	at com.sap.cloud.sdk.cloudplatform.thread.ThreadContextAccessor.tryGetCurrentContext(ThreadContextAccessor.java:84)
> 	at com.sap.cloud.sdk.cloudplatform.servlet.DefaultRequestFacade.tryGetCurrentRequest(DefaultRequestFacade.java:28)
> 	at com.sap.cloud.sdk.cloudplatform.servlet.RequestAccessor.tryGetCurrentRequest(RequestAccessor.java:87)
> 	at com.sap.cloud.sdk.cloudplatform.security.DefaultAuthTokenFacade.tryGetCurrentToken(DefaultAuthTokenFacade.java:129)
> 	at com.sap.cloud.sdk.cloudplatform.security.AuthTokenAccessor.tryGetCurrentToken(AuthTokenAccessor.java:100)
> 	at com.sap.cloud.sdk.cloudplatform.security.AuthTokenAccessor.getCurrentToken(AuthTokenAccessor.java:81)
> 	at com.sap.grc.automatedprocedures.systemtestshelper.configuration.RequestContextExecutorConfiguration.testhelperRequestContextExecutor(RequestContextExecutorConfiguration.java:35)
>

**Comment by MatKuhr** [comment]
You need to pass down the thread context. Here is how you do it: https://sap.github.io/cloud-sdk/docs/java/features/multi-tenancy/multi-tenancy-thread-context#running-asynchronous-operations

**Comment by RuchiDhiman** [comment]
In the documentation a variable customTenant is referenced. How is it initialised? In our case we need instance of AuthToken. For which I called method AuthTokenAccessor.getCurrentToken(); that dumps with the exception shown above.

**Comment by MatKuhr** [comment]
Please check again, the tenant is only needed in case you want to pass down a tenant _**only**_, without any other information.

The default use case is to just pass down the thread context with all information (tenant, user, auth token etc.). For that it is sufficient to:

```java
ThreadContextExecutor executor = new ThreadContextExecutor();
Callable operationWithContext = () -> executor.execute(() -> operation());

invokeAsynchronously(operationWithContext);
```

**Comment by RuchiDhiman** [comment]
Does an instance of ThreadContextExecutor have to be created for every time an asynchronous operation is started or can one maintain it as a singelton?

**Comment by MatKuhr** [comment]
Hi @RuchiDhiman, I hope the above solved your issue. Otherwise, please re-open this item. Thanks!
