### ISSUE TITLE
Support link for SAP Cloud SDK for Java points to "Page Not Found"

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk#1219]
In the footer of each page at https://sap.github.io/cloud-sdk/ there is a link "Support" for the SAP Cloud SDK for Java it points to:

https://sap.github.io/cloud-sdk/docs/java/support-java

but currently this page shows: "Page Not Found".

**Comment by jjtang1985** [comment]
Hi @gregorwolf ,

Thank you very much for reporting the broken link.
I can confirm and we will work on it soon.

For those who are searching for support or for SDK developers who will work on it, here are some hints.
- The real support link is here: https://sap.github.io/cloud-sdk/docs/java/support
- We do have a redirect config from '/support-java' to '/support', which is obviously not working if you open the page from the home page. However, it does work, if you open a new tab from the home page of simply open it by clicking the second link provided by @gregorwolf . Therefore, we should keep the redirect config and fix the link in the home page.

**Comment by MatKuhr** [comment]
Thanks for reporting this! Fixed via https://github.com/SAP/cloud-sdk/pull/1221 :)
