### ISSUE TITLE
Is the On-Premise Connectivity in Kubernetes still not available for Customers?

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk#1251]
All Documentation version of the Guide Migrate a Cloud Foundry Application to a Kubernetes show a warning in the section [On-Premise Connectivity](https://sap.github.io/cloud-sdk/docs/js/v3/guides/kubernetes#on-premise-connectivity) that:

> On-Premise connectivity in Kubernetes is currently not available for external SAP customers.

Is this still correct? I think I did deploy the `Connectivity Proxy` already in my BTP Free Tier environment.

**Comment by MatKuhr** [comment]
Hi Gregor, the content is indeed out of date. We have an update pending: https://github.com/SAP/cloud-sdk/pull/1120

We have an alignment with the colleagues from BTP connectivity next week, after than we should be able to publish the update.

**Comment by MatKuhr** [comment]
Closing this, as [the documentation](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/on-premise) has been updated in the meanwhile.
