### ISSUE TITLE
Security vulnerability for common-codec jar using  com.sap.cloud.sdk version 4.6.0

### ISSUE THREAD

**Issue by mkmishra89** [SAP/cloud-sdk#1257]
Hi Team,
We are working for BTP.

We are using cloud sdk version 4.6.0 and we are getting security vulnerability for commons-codec:1.11.

![image](https://user-images.githubusercontent.com/97277843/217212846-eba6743c-d9a5-4ee9-9e44-876695f54945.png)

![image](https://user-images.githubusercontent.com/97277843/217214323-8b740e38-1134-4da4-99fe-14175c7c2b44.png)

Could you please fix it and share the latest version to us.

**Comment by CharlesDuboisSAP** [comment]
Dear User,

We do not publish a specific version for `commons-codec` in our bom.
The fix would be to override the version in your pom:
```xml
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>commons-codec</groupId>
				<artifactId>commons-codec</artifactId>
				<version>1.15</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
```

Let me know if this fixes it.

Best regards,
Charles Dubois

**Comment by mkmishra89** [comment]
We tried this one but it is not working. We are building one application and using that application as a dependency for other service. In other service while creating the instance of ScpCfDestinationLoader loader = new ScpCfDestinationLoader(); we are getting exception. java.lang.NoClassDefFoundError

**Comment by CharlesDuboisSAP** [comment]
Dear User,

The dependency needs to be defined in every application pom, or, in the common parent pom if it exists.
The parent pom of the SAP Cloud SDK uses this fix.

If it doesn't fix the error, I would need the full stack trace.

Best regards,
Charles Dubois

**Comment by newtork** [comment]
HI @mkmishra89,

Have you been able to resolve the dependency issue? If not please feel free to share your `mvn dependency:tree`.

Kind regards
Alexander
