### ISSUE TITLE
How to create an SAP app for success factors?

### ISSUE THREAD

**Issue by Tobjoern** [SAP/cloud-sdk#1290]
Hello,
we are pretty new to the SAP environment, so sorry if this is a basic question!

We operate a job-platforms and some of our business clients asked for an integration with SAP Success Factors.

The general workflow should look like this:

- 1. User applies through our platform

- 2. We send that user's CV and metadata to success factors via the API contract (https://api.sap.com/api/RCMCandidate/resource)

From my understanding, we need an authentication token in order to authorize our call to our user's candidate resources

What would be the best way to integrate with success factors? Multiple business customers are asking for the integration, what would be our next steps, do we create a developer app?

We just need a standard oauth 2 procedure with the correct permissions to make the appropriate API calls.

I'm looking forward to your help!

**Comment by newtork** [comment]
Hi @Tobjoern,

We cannot give full guidance or proper consultancy on the specific use case. But we can help if you are interested in...
* generating source files to improve development experience and convenience for _Success Factors_ service consumption.
* using OData client(s) to properly define queries and handle serialization/deserialization for requests and responses.
* convenience API to interact with BTP services, e.g. `destination`, `xsuaa` and `connectivity` (in case of SAP S/4HANA OnPremise).
* convenience API to use different OAuth2 authentication flows explicitly and implicitly.

You can find everything in our documentation portal:
https://sap.github.io/cloud-sdk/

For further help it would be interesting to us whether you are...
* facing a specific technical problem
* deploying to Cloud Foundry or somewhere else
* using Java or JavaScript
* using some kind of application framework already

Kind regards
Alexander

**Comment by Tobjoern** [comment]
Thanks I just created a support ticket, to get the oauth flow working.

We are looking to use Typescript in the backend (no specific framework).
In regards to the deployment, we would prefer to deploy the application code on our own servers and just
interact with the API via the appropriate auth tokens.

Kind regards
Tobias

**Comment by marikaner** [comment]
In that case, I would close this issue for now. Feel free to share your feedback once you are onboarded and let us know if you need support with concrete issues.
