### ISSUE TITLE
WhiteSource security vulnerability finding regarding lodash 4.17.15

### ISSUE THREAD

**Issue by jjtang1985** [SAP/cloud-sdk#135]
We received such feedback regarding a WhiteSource finding:

> Hi colleagues,
>
> Recently our project encountered a WhiteSource security vulnerability (WS-2020-0070) of NodeJS component "lodash-4.17.15".
>
> Can you please help fix it?
> Related Cloud SDK component: @sap-cloud-sdk/util
> Version: 1.20.0

**Comment by jjtang1985** [comment]
There is an open issue [here](https://github.com/lodash/lodash/issues/4738).

**Comment by HoffmannThomas** [comment]
Looking at the lodash track record (4738,4518, etc.) you should consider not using it at all...

**Comment by marikaner** [comment]
We aren't, but we have a dependency that has a dependency that uses it.

**Comment by naresh-pidugu** [comment]
Is there a fix for the issue reported here ?

**Comment by avidj** [comment]
Hello @marikaner,
now we have the problem this dependency comes into our project (SAP Graph) transitively through the cloud sdk while the lodash maintainer(s) seem reluctant to fix the issue. Therefore, our mandatory whitesource scans fail due to that transitive dependency.

**Comment by marikaner** [comment]
Thanks for letting us know. Yeah, the reluctance to fix this issue on lodash side is a major problem.  I was hoping for them to come around eventually. We know that this is occurring transitively through `winston > async > lodash`. `async` already got rid of `lodash`. `winston` already updated to the latest version of `async` on their master, but did not make a new release for this yet. There already is a ticket in the winston repo: https://github.com/winstonjs/winston/issues/1812.
As `async` is just a small convenience library it might be possible, that winston is compatible with a newer version, then I might provide a hacked hotfix. I will let you know.

**Comment by marikaner** [comment]
We solved this manually and will probably make a new release next week.
