### ISSUE TITLE
findbugs dependency removal

### ISSUE THREAD

**Issue by mikolayek** [SAP/cloud-sdk#1406]
## Issue Description
My project has been scanned by blackduck where we have in dependency `com.sap.cloud.sdk.cloudplatform:cloudplatform-core:4.16.0`

When you run `mvn dependency:tree` we see that there is a dependency to findbugs:

```
+- com.sap.cloud.sdk.cloudplatform:cloudplatform-core:jar:4.16.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
```

BlackDuck marks `jsr305` as High prio operational issue. 
I have checked library code and couldn't find places where that lib is used. 

### Impact / Priority

BlackDuck marks `jsr305` as High prio operational issue. 

## Project Details

- SAP Cloud SDK Version: 4.16.0

- Link to GitHub repository: <your link here>
- Project type, for example:
  - [ ] CAP Project
  - [X] SAP Cloud SDK Maven Archetype
  - [ ] None of the above:
- Platform:
  - [ ] Cloud Foundry
  - [ ] Neo
  - [X] None of the above: Kyma

**Comment by newtork** [comment]
With `4.18.0` we removed the `jsr305` from the dependency tree.

There is some exception for code generators, that will need the dependency at `compile` scope but for regular use-cases like yours, this should be fixed.

I'm closing this issue for now, please let us know if there's something else to improve :+1:
