### ISSUE TITLE
Email client in JAVA

### ISSUE THREAD

**Issue by metabit1000** [SAP/cloud-sdk#1493]
I miss a mail client functionalty as it exists in the javascript version. 

I'm trying to use a on-premise mail server using SAP CLOUD SDK JAVA. I didn't find any example of how to do it. I know that in case of javascript there's "email-client" (https://sap.github.io/cloud-sdk/docs/js/features/mail-client#on-premise-destination), but for java?

I think it would be very useful to have this functionality in JAVA too. It's not straightforward to do the same without this functionality.

Thank you for your consideration!

**Comment by jjtang1985** [comment]
Hi @metabit1000 ,

Thank you for reaching out.

>I'm trying to use a on-premise mail server using SAP CLOUD SDK JAVA. I didn't find any example of how to do it.
Yes, you are right. The Java SDK does not offer such feature.
For the time being, I guess you can get a mail destination, then follow the SAP BTP [documentation](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/using-tcp-protocol-for-cloud-applications?locale=en-US).

>Thank you for your consideration!
We will discuss this feature request in the team.
However, most likely, this will not happen in this year.

Best regards,
Junjie

**Comment by mperumalswamy** [comment]
Any update on this feature?

**Comment by jjtang1985** [comment]
We discussed the topic in the team.
Unfortunately, we have no plans for working on that in the near future.
I'll close this ticket as Java SDK is now open sourced and if needed, the feature requests should be opened [there](https://github.com/SAP/cloud-sdk-java/issues).
