### ISSUE TITLE
Calling a BAPI

### ISSUE THREAD

**Issue by MarcusSchoelzel** [SAP/cloud-sdk#151]
## Issue Description

I have created a TomEE-Java project based on the description in the chapter [Call a BAPI/RFC Module](https://sap.github.io/cloud-sdk/docs/java/features/bapi-and-rfc/bapi-and-rfc-overview) of the Cloud SDK for Java documentation.

- I am calling a BAPI in a S/4HANA on-premise system
- The project is deployed to SAP BTP Cloud Foundry Environment
- The connection to the backend is established via cloud connector and destination service
- Security with XSUAA is activated (uncommented the part in web.xml as generated by the archetype) in the project and the WebServlet is protected by a HttpConstraint
- Approuter is used for accessing the service

When deployed all works as expected.

Now to my questions/problems that i have currently and that i have observed during implementation:

1. After i activated the security with XSUAA the integration test, that is generated by the archetype and that i have adapted to my implementation, is getting an error "HTTP Status 403 – Forbidden". I had a look at the MockUtil-Class but i could not figure out how or if it is possible to mock the XSUAA. Is there a example or documentation how to achieve this? I want to run the test with "auth strategy dummy" like in CAP or something similar like that.
2. Is it possible to mock the S/4HANA destination with test data in a unit test? Is there a example or documentation for that?
3. What i really want, is to call a BAPI from a CAP JavaScript project directly. Will this be possible in the future?
4. If not, i now have a plain REST service that calls the BAPI. Do you have a recommendation how i call this service from a CAP JavaScript project? As a side note, i have two subprojects in a monorepo, one is the Java service that calls the BAPI and the other one is the CAP JavaScirpt project. How do i connect the both in the best and easiest way. I will deploy them alltogether as a MTA.
5. First i started with a SpringBoot project, also from the getting started section of the Cloud SDK docu. After deploying the project to CloudFoundry i realized that the JCo in the sap_java_buildpack is only installed when a war is deployed. As i am not so familiar with Java and the SpringBoot arcehtype is generated with JAR deployment i gave up on that. Maybe you can spent a section about that in the documentation. This would also mean that you cannot easily use BAPI calls in a CAP Java project as this is based on SpringBoot.

### Impact / Priority

Affected development phase: Getting Started
Impact: Blocked
Timeline: no timeline

**Comment by artemkovalyov** [comment]
Hi @MarcusSchoelzel,

These are quite some topics to discuss. Let's start with the most pressing one and get as much context about it as possible. Would it be solving the 403 in the tests? Can you attach some logs and code snippets of your destination configuration?

Another point to clarify is: BAPIs are supported only by the Java SDK, it would hardly be soon supported by the JS SDK. You can look at this JS library if you need them for Node: https://github.com/SAP/node-rfc

Looking forward to solving your issues soon.

**Comment by newtork** [comment]
@MarcusSchoelzel asked:

> Is it possible to mock the S/4HANA destination with test data in a unit test? Is there a example or documentation for that?

In your tests, you can use the [experimental](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java/#3330---november-20-2020) `DefaultDestinationLoader` which allows you to attach a custom destination. Afterwards you can prepend the new destination loader to the accessor logic, like in the following example:
```java
DefaultHttpDestination dest = DefaultHttpDestination.builder("http://sap.com").name("dest1").build();
DefaultDestinationLoader loader = new DefaultDestinationLoader().registerDestination(dest);
DestinationAccessor.prependDestinationLoader(loader);
```
If you want to replace all implicit loading, you can set/overwrite the main loader
```java
DestinationAccessor.setLoader(loader);
```
If this works out for you and you find it suitable for your application tests, then we would invest some time into the public documentation on this class.

---

If you want to mock the behavior/payload on the custom destination, then we currently recommend using [WireMock](http://wiremock.org/docs/getting-started/). You could adjust your destination instantiation like the in following:
```java

@Rule
public WireMockRule server= new WireMockRule(wireMockConfig().dynamicPort());

// or

WireMockServer server = new WireMockServer(wireMockConfig().dynamicPort());

// resulting in

DefaultHttpDestination dest = DefaultHttpDestination.builder("http://localhost:"+server.port()).name("dest1").build();
```

---

@MarcusSchoelzel asked:

> Do you have a recommendation how i call this service from a CAP JavaScript project? As a side note, i have two subprojects in a monorepo, one is the Java service that calls the BAPI and the other one is the CAP JavaScript project. How do i connect the both in the best and easiest way?

To me this all sounds reasonable. Maybe my assumption sounds naïve, but couldn't you just call the URL of your REST application? Or is there a specific problem you are facing? In case you see an issue with the (presumably) unnecessary Java component, then I would support @artemkovalyov advice to check out this node library, maybe it helps you in this regard. In case it does, please let us know.

---

@MarcusSchoelzel asked:

> [...] JCo in the sap_java_buildpack is only installed when a war is deployed. As i am not so familiar with Java and the SpringBoot arcehtype is generated with JAR deployment i gave up on that.

Have you seen the following [point from our documentation](https://sap.github.io/cloud-sdk/docs/java/features/bapi-and-rfc/bapi-and-rfc-overview/#boundary-conditions-and-edge-cases)?

> _There have been issues with finding JCo classes in a Spring Boot project. In such cases using the "traditional deployment" of Spring solved the problem. Thereby you deploy a war file instead of a jar file and you use Tomcat as the servlet container._

Would you like us to explain in more detail how this can be achieved?

Kind regards
Alexander

**Comment by MarcusSchoelzel** [comment]
@artemkovalyov and @newtork invited you to the private project.

@artemkovalyov:
- The 403 error to solve would be nice for local testing. It's about to mock the XSUAA authentication. Can this be achieved with the MockUtil class from the Cloud SDK?
- The node-rfc library is a good hint, didn't know it. But it has some prerequisites and that raises the question how to deploy such a project to BTP CF?

@newtork 
- WireMock looks promising, i'll have to investigate on that.
- My problem is currently to call that REST service from a CAP project. Was not able to find a documentation or example that describes the best way to do that with the CDS API. The examples are all based on Odata and service descriptions.
- I saw that point in the documentation. But i think that all SpringBoot projects that were created in the context of Cloud SDK or CAP with SpringBoot will have that issue. And it would be great if there would be a description how to change a SpringBoot project to work with the sap_java_buildpack and the JCo connector. If this would be possible with a CAP Java project i would switch to that flavour because then i can benefit from the convenience of CAP.

**Comment by newtork** [comment]
> @artemkovalyov and @newtork invited you to the private project.

Where would I see the invitation?

> The 403 error to solve would be nice for local testing. It's about to mock the XSUAA authentication. Can this be achieved with the MockUtil class from the Cloud SDK

Can you share example code? Otherwise the question is too generic I'm afraid. I didn't have problems when I tried it with _hello-world_.

>  to call that REST service from a CAP project [...]

I'm not an expert on the CAP project, hence I would suggest asking the [CAP team](https://cap.cloud.sap/docs/java/) directly on how to call generic REST endpoints.

> If this would be possible with a CAP Java project [...]

It is possible AFAIK, I'll forward your question to my colleagues.

**Comment by MarcusSchoelzel** [comment]
@newtork You should get an e-mail from github

**Comment by newtork** [comment]
> If this would be possible with a CAP Java project [...]

According to this [comment](https://stackoverflow.com/questions/61073716/define-scp-destination-for-s4hana-bapi-call-with-cloud-sdk/61120396#comment108595003_61120396)...
> There are two places that you need to adapt in cloud sdk project. One is `pom.xml` in application module. Add `<packaging>war</packaging>`. The other is `manifest.yaml` file in parent project. Modify the war file path and then change the run time from `main` to `tomcat`

**Comment by MarcusSchoelzel** [comment]
Finally i have managed to deploy a CAP Java project on BTP Cloud Foundry with a BAPI call using JCo.

Following changes have to be made to a project that was generated from the CAP Java archetype (cds-services-archetype):

1. Change packaging from jar to war in pom.xml

`<packaging>war</packaging>`

2. Add maven-war-plugin to build plugins in pom.xml

``` xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.3.1</version>
                <configuration>
                    <attachClasses>true</attachClasses>
                </configuration>
            </plugin>
```

3. Add the SpringBootServletInitializer to the SpringBoot application startup

``` java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;

@SpringBootApplication
public class Application extends SpringBootServletInitializer {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}

}
```

4. Change the deployment configuration in mta.yaml to java.tomcat and adjust the build-result path

``` yaml
  - name: rfc-srv
    type: java.tomcat
    path: rfc
    properties:
      USE_JCO: true
    requires:
      - name: uaa
      - name: destination
      - name: connectivity
    provides:
      - name: srv_api_rfc
        properties:
          url: ${default-url}
    parameters:
      memory: 1024M
    build-parameters:
      build-result: srv/target/rfc.war
      builder: custom
      commands:
        - mvn clean package install
```

With these changes the Java application is starting in the Cloud Foundry container. Depending on the deployment configuration the application can boot as SpringBoot with embedded Tomcat or as Servlet on a Tomcat.

This solves the authentication issue with XSUAA because with CAP Java it is easy to mock the authentication when running local.

Maybe this information can be incorporated into a guide or documentation.

**Comment by newtork** [comment]
> Maybe this information can be incorporated into a guide or documentation.

Thank you so much for the explanation! We will definitely do that.

**Comment by newtork** [comment]
Wondering, where did you get the `type: java.tomcat` from? We expected `buildpacks: - sap_java_buildpack` to suffice?

**Comment by MarcusSchoelzel** [comment]
> Wondering, where did you get the type: java.tomcat from? We expected buildpacks: - sap_java_buildpack instead.

This is from help.sap.com - SAP HANA Developer Guide for SAP HANA XS Advanced Model - MTA Deployment Descriptor Syntax:
https://help.sap.com/viewer/4505d0bdaf4948449b7f7379d24d0f0d/2.0.05/en-US/4050fee4c469498ebc31b10f2ae15ff2.html#loio4050fee4c469498ebc31b10f2ae15ff2__table_sj5_vdb_kv

**Comment by Emdee89** [comment]
This is now documented: https://sap.github.io/cloud-sdk/docs/java/guides/spring-boot-war-deployment
