### ISSUE TITLE
Question: how to get http header info from a WrappedDestination

### ISSUE THREAD

**Issue by ktesnim** [SAP/cloud-sdk#1548]
Hi ,

As described by the following [documentation ](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/destination-service#http-destinations), I the get destination by calling  

`Try<Destination> destinationTry = tryGetDestination(destinationName);
        if (destinationTry.isSuccess()) {
            try {
                if (LOGGER.isDebugEnabled()) {
                    LOGGER.debug("Successfully retrieved destination {}", sanitize(destinationName));
                }
                return destinationTry.get();`

 which return as  result a  **com.sap.cloud.sdk.cloudplatform.connectivity.WrappedDestination**.

My question is there any option to get **httpHeaders** info from the returned object?

* SDK Version: 4.22.0

* Link to GitHub repo: https://github.tools.sap/CALMRun/x-rn-service
* Project type, for example:
    * [x] CAP Project
    * [ ] SDK Maven Archetype
    * [ ] None of the above:
* Platform:
    * [ ] Cloud Foundry
    * [x] Deploy with Confidence (Cloud Foundry)
    * [ ] None of the above:

Any help from your side will be appreciated .

Best regards,
Tesnim

**Comment by jjtang1985** [comment]
I'll close this duplicate issue.
Please track [here](https://github.com/SAP/cloud-sdk-java/issues/84).
