### ISSUE TITLE
localhost ECONNREFUSED on NodeJS 18

### ISSUE THREAD

**Issue by hosssa** [SAP/cloud-sdk#1571]
On the [On-Premise Connectivity](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/on-premise) page its explained how to set up an SSH tunnel and to change `onpremise_proxy_host` to `localhost` in VCAP_SERVICE.

However, there is an issue with NodeJS 18 (>=17 I guess) that http connections to localhost result in an ECONNREFUSED error. 
[Unable to connect to establish a TCP connection (ECONNREFUSED) #40702](https://github.com/nodejs/node/issues/40702)
The simple workaround is to use the IP `127.0.0.1` instead. 

Maybe you can update or mention this in the documentation.

Thanks & Regards,
Frank

**Comment by jjtang1985** [comment]
Hi @hosssa ,

Thanks for raising up!
We highly appreciate your investigation and updates.
As this is an open source repository, would you like to contribute to our documentation by opening a PR?

Just want to point out, it seems they've [fixed the node 20](https://github.com/nodejs/node/issues/40702#issuecomment-1599950785).

Best regards,
Junjie

**Comment by MatKuhr** [comment]
@jjtang1985 can this be closed then?
