### ISSUE TITLE
Webpack bundling failure for browser because of "node:url" is not handled by plugins

### ISSUE THREAD

**Issue by magician-margatroid** [SAP/cloud-sdk#1578]
Hi, according to config in doc [Use the SAP Cloud SDK in the Browser](https://sap.github.io/cloud-sdk/docs/js/guides/browser), at present, the bundling in my environment will fail with this error:
```bash
Module build failed: UnhandledSchemeError: Reading from "node:url" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

The webapp to reproduce this phenomenon: [cloud-sdk-in-react](https://github.com/magician-margatroid/cloud-sdk-in-react) with steps listed on its [README.md](https://github.com/magician-margatroid/cloud-sdk-in-react/blob/master/README.md).

Taking the advantage of [normal-module-replacement-plugin](https://webpack.js.org/plugins/normal-module-replacement-plugin/) could be a possible solution dealing with this issue.

**Comment by tomfrenken** [comment]
Hey @magician-margatroid,

This issue was introduced when we started prefixing our node dependencies with `node:` as this has recently become a best practice, however, we failed to realize this might cause issues in the browser.

Thank you very much for your in-depth investigation as well as your proposed solution, we will adjust our documentation.

**Comment by magician-margatroid** [comment]
> Hey @magician-margatroid,
> 
> This issue was introduced when we started prefixing our node dependencies with `node:` as this has recently become a best practice, however, we failed to realize this might cause issues in the browser.
> 
> Thank you very much for your in-depth investigation as well as your proposed solution, we will adjust our documentation.

Hi @tomfrenken thx a lot and it's my pleasure.
