### ISSUE TITLE
Call a BAPI/RFC Module Warning statement

### ISSUE THREAD

**Issue by bsrdjan** [SAP/cloud-sdk#1592]
The warning on [Call a BAPI/RFC Module page](https://sap.github.io/cloud-sdk/docs/java/features/bapi-and-rfc/overview) sounds like RFC is supported by JCo only:

> WARNING
RFC, JCo and SOAP modules are deprecated. These modules will be kept for version 5 as well, but will be removed in the future. Please consider searching for an OData based service (e.g., via SAP Business Accelerator Hub) as possible replacement, and SDK offers OData type safe clients (both OData v2 and v4). If you have to use JCo or RFC, here is the [documentation](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/invoking-abap-function-modules-via-rfc) about how to consume ABAP functions via RFC, using JCo.

Just like JCo for Java, SAP RFC connectors are provided for Node.js and Python platforms: [SAP/node-rfc](https://github.com/SAP/node-rfc) and [SAP/PyRFC](https://github.com/SAP/PyRFC). For the sake of completeness, the warning could be perhaps re-formulated as:

> WARNING
RFC, JCo and SOAP modules are deprecated. These modules will be kept for version 5 as well, but will be removed in the future. Please consider searching for an OData based service (e.g., via SAP Business Accelerator Hub) as possible replacement, and SDK offers OData type safe clients (both OData v2 and v4). If you have to use RFC, you can use [JCo RFC connector](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/invoking-abap-function-modules-via-rfc) for Java platform, with SAP Cloud Connector, or [SAP/PyRFC](https://blogs.sap.com/2023/10/30/abap-rfc-connectivity-from-btp-python-buildpack/) and [SAP/node-rfc](https://blogs.sap.com/2023/10/26/abap-rfc-connectivity-from-btp-node.js-buildpack/) for Python and Node.js platforms, with SAP Business Connector.

**Comment by jjtang1985** [comment]
Thank you @bsrdjan for raising this up.
I incorporated your suggestion into our docs.
