### ISSUE TITLE
Support for Oauth client credentials flow send as basic auth header

### ISSUE THREAD

**Issue by Praveen-Varma** [SAP/cloud-sdk#1643]
**[OPTIONAL] Survey**
Please, help us making the SAP Cloud SDK better by taking our [survey](https://sapinsights.eu.qualtrics.com/jfe/form/SV_0P69X6kJ0Pdxqbc).
It takes less than 3 minutes :)

**Is your feature request related to a problem? Please describe.**
Facing 401 error when Destination is maintained as environment variable for connecting to Neo platform. 
[{"type": "HTTP", "name": "MyDestination", "proxyType": "Internet", "authentication": "OAuth2ClientCredentials", "url": "https://tenant-tmn.hci.usx.hana.ondemand.com/api/v1", "tokenServiceUser": "tokenserviceuser", "tokenServicePassword": "tokenservicepass", "clientId": "tokenserviceuser", "clientSecret": "tokenservicepass", "tokenServiceURL": "https://oauthasservices-tenant.usx.hana.ondemand.com/oauth2/api/v1/token?grant_type=client_credentials", "tokenService.addClientCredentialsInBody": "false" }]

**Describe the problem and a solution you'd like**
Support for client credentials flow with basic auth header

**Describe alternatives you've considered**

**Additional context**

**Comment by mr-flannery** [comment]
Hi @Praveen-Varma ,

could you please share a code snippet and a stacktrace? Thanks!
