### ISSUE TITLE
generator produces uncompilable files in version 1.21.0

### ISSUE THREAD

**Issue by nocheintobi** [SAP/cloud-sdk#166]
**Describe the bug**
When generating an OData Client using the @sap-cloud-sdk/generator in version 1.21.0, compilation of the generated VDM files fails. Works fine in version 1.20.1 and earlier.

**To Reproduce**
Place the attached edmx.xml in folder `edmx` inside a sap-cloud-sdk project and run `sap-cloud-sdk generate-odata-client -i edmx -o src/vdm`
When running `tsc`, there will be lots of argument mismatches (see compilation_errors.txt).

When switching the globally installed @sap-cloud-sdk/generator back to 1.20.1, everything works as expected.

Versions in use:
Node: 10.18.0
NPM: 6.14.2
[compilation_errors.txt](https://github.com/SAP/cloud-sdk/files/4700784/compilation_errors.txt)
[edmx.xml.txt](https://github.com/SAP/cloud-sdk/files/4700788/edmx.xml.txt)

TSC: 3.9.2
@sap-cloud-sdk/cli@0.1.8
@sap-cloud-sdk/generator@1.21.0

**Comment by marikaner** [comment]
Hello @nocheintobi,

thanks for reporting this. I will take a look at this and get back to you as soon as possible.

**Comment by marikaner** [comment]
Hey @nocheintobi,

it seems that you are using an older version of the `core` package, but it should be at least version `1.21.0`. OData clients generated by the generator with version `1.21.0` need a core with the same version at least. The generator should generate a package.json with the correct dependency. Are you overwriting this version somehow?

**Comment by nocheintobi** [comment]
Hey @marikaner,
I did not overwrite the version after generating the VDM, but in deed, I've been using core in version  "^1.20.1". When upgrading to 1.21.0 compile errors were gone.

Thanks a lot for your help and fast response!!!
