### ISSUE TITLE
Link to Destination Configuration for Mail Client Points to BTP ABAP Documentation

### ISSUE THREAD

**Issue by sebastianesch** [SAP/cloud-sdk#1709]
In the section "What's the difference" of the "Mail Client" documenation (https://sap.github.io/cloud-sdk/docs/js/features/mail-client#whats-the-difference), instead of linking to the documentation about sending E-Mails from the ABAP Environment on BTP (https://help.sap.com/docs/btp/sap-business-technology-platform/integration-and-connectivity-sending-mails-using-smtp) it would make more sense to link to the BTP Connectivity documentation about Mail Destinations (https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/create-mail-destinations) directly.

The second link appears in the ABAP documentation, but the intermediary step confuses more than it helps. Unfortunately, neither documentation explains the properties that have to be set for a Mail destination, but I guess I'll create a separate issue in the BTP Connectivity documentation for this issue (see https://github.com/SAP-docs/btp-connectivity/issues/3).

Kind regards,
Sebastian

**Comment by deekshas8** [comment]
Hi @sebastianesch ,

Thank you for your suggestion, I agree the current link it not entirely correct. I'll update the link.
