### ISSUE TITLE
SAP OData client - Access MessageProcessingLogs in BTP Integration Suite- How to get (link to) attachment

### ISSUE THREAD

**Issue by JHopmann** [SAP/cloud-sdk#1766]
Dear Community, dear SUpport.

I have generated an OData V2 client with the maven-approach, in Eclipse.

Connecting the API in Integration Suite is running so far, the objects are available as one can see the details from the "Monitor Message Processing".

Here is a code-snippet:

```java
var destination = DefaultHttpDestination.builder("https://<somename>****.it-cpi024.cfapps.eu10-002.hana.ondemand.com")
        .authenticationType(AuthenticationType.BASIC_AUTHENTICATION)
        .basicCredentials(new BasicCredentials("joerg.hopmann@<mycustomer_in_fra.com", "****"))
        .build();

// perform actual test
final MessageProcessingLogsService service = new DefaultMessageProcessingLogsService().withServicePath("/api/v1/");

//first get the total number
long l = service.getAllMessageProcessingLogs()
        .count()
        .executeRequest(destination);

final List<MessageProcessingLog> mpl = service.getAllMessageProcessingLogs()
        .executeRequest(destination);

String loggerString = null;
for (MessageProcessingLog mpl_iter : mpl)   {
    loggerString = mpl_iter.getIntegrationFlowName() + " : ";
    List<MessageProcessingLogAttachment> mplAttachments = mpl_iter.fetchAttachments();
    if (mplAttachments.size() > 0)  {
        loggerString += " Attachment : Type : ";
        loggerString += mplAttachments.get(0).getContentType() + " Content : ";
        for (MessageProcessingLogAttachment mpla : mplAttachments)  {
            loggerString += mpla.toString() + ".";
        }
        logger.info(loggerString);
    }
}
```

One example output from ...Attachment.tostring() is as following:

```
2024-04-01T06:24:30.471+02:00  INFO 10396 --- [           main] c.s.c.s.d.c.HelloWorldController         : CDCContactConsent :  
Attachment : Type : text/plain 
Content : MessageProcessingLogAttachment(super=VdmObject(customFields={}, changedOriginalFields={}), id=636f(...)326638, messageGuid=AGX4Hj1qvhfsv3oEWm_lMo5d9UBy, timeStamp=2024-03-18T10:58:06, name=Message, contentType=text/plain, payloadSize=339).
```

I was expecting / hoping to see "the attachment" here, but - similar to the Monitoring - there are only properties of the log-entries, NOT the content.

Accessing an attachment via Postman is possible with the following URL:

```
https://.cfapps.eu10-002.hana.ondemand.com/api/v1/MessageProcessingLogs(%27AGX4Hj1qvhfsv3oEWm_lMo5d9UBy%27)/Attachments
```

By calling `service.MessageProcessingLogAttachmentByKey` I get a 404 from BTP. Anyway, I assume the resulting object would not contain the content (but only the properties).

The way the GUID is given in the URL in the mid of the URL "/MessageProcessingLogs"GUID"/Attachments" is - let's say - a little bit uncommon. and especially the payload is given as an octet-stream. How can I handle this? This seems not the way I want...

So I was searching for a way to get this in the OData-client. So far I found some classes which may (or may not) help my, e.g.:

```java
package com.sap.cloud.sdk.datamodel.namespaces.messageprocessinglogs.link;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.namespaces.messageprocessinglogs.MessageProcessingLogAttachment;
import com.sap.cloud.sdk.datamodel.namespaces.messageprocessinglogs.selectable.MessageProcessingLogAttachmentSelectable;
import com.sap.cloud.sdk.datamodel.odata.helper.EntityLink;
import com.sap.cloud.sdk.datamodel.odata.helper.VdmObject;


/**
 * Template class to represent entity navigation links of {@link com.sap.cloud.sdk.datamodel.namespaces.messageprocessinglogs.MessageProcessingLogAttachment MessageProcessingLogAttachment} to other entities. Instances of this object are used in query modifier methods of the entity
 * fluent helpers. Contains methods to compare a field's value with a provided value.
 * 
 * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData
 * field names, so use the constructor with caution.
 * 
 * @param <ObjectT>
 * Entity type of subclasses from {@link com.sap.cloud.sdk.datamodel.odata.helper.VdmObject VdmObject}.
 * 
 */
public class MessageProcessingLogAttachmentLink<ObjectT extends VdmObject<?> >
    extends EntityLink<MessageProcessingLogAttachmentLink<ObjectT> , MessageProcessingLogAttachment, ObjectT>
    implements MessageProcessingLogAttachmentSelectable
{
```

This matches with the Monitoring frontend in BTP, there is also a link to download the attachment (as text/plain).

My question(s):

Is it possible to download the attachment and if so, is this the way to go?
How do I use this class? Is there an example somewhere? Documentation? Knowledge?
Any help appreciated and thanks in advance. Kindest regards Jörg Hopmann

**Comment by MatKuhr** [comment]
Hi Jörg,

I'm not familiar with the specific OData service you are trying to use. In case the service metadata available on [api.sap.com](https://api.sap.com/), could you please share the link? If not, can you otherwise somehow share the metadata? Without the metadata and without knowing more about the service it's hard to know how the service is intended to be used...

> The way the GUID is given in the URL in the mid of the URL "/MessageProcessingLogs"GUID"/Attachments" is - let's say - a little bit uncommon

You can check [this article](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) on how accessing entities in OData works and how it is (slightly) different from the standard REST `/resource/{id}/nestedResource` format.

In particular, consider reading about the meaning of **`$expand`** and how you can [use it with the SAP Cloud SDK](https://sap.github.io/cloud-sdk/docs/java/features/odata/v2-vdm-client#select). Depending on how the OData service is defined, selecting the relevant fields may solve your requirements.

**Comment by JHopmann** [comment]
Hallo Matthias,

 

vielen Dank für deine Antwort. Ich habe dir parallel eine Einladung auf LinkedIn gesendet. Hoffe es trifft auf Akzeptanz so wie auch das „Du“ hoffentlich OK ist.

 

Meine Frage zu den MessageProcessingLogs zielt auf folgendes Problem ab:

Ich habe die vdm-sourcen mittels maven-generator erzeugt, aus der API-Spezifikation, die Struktur mal als Zip an diese Mail angehängt, ich hoffe das geht über github nicht verloren:

 



 

Klar das du dich da jetzt nicht tief für mich einarbeitest, aber meine Hoffnung ist das du vlt Tipps hättest.

 

Ich kann die API auf der BTP abfragen und Objekte wie z.B. 

com.sap.cloud.sdk.datamodel.namespaces.messageprocessinglogs.MessageProcessingLogAttachment

instanziieren.

 

Das geschieht wie folgt: (Ich mache es mal explizit hier, hoffe es passt):

 

List<MessageProcessingLogAttachment> mplAttachments = mpl.fetchAttachments();

   if (mplAttachments.size() > 0)  {

 

Also schauen wieviele Attachments sind drin. Mehr als 0?

Dann:

 

for (MessageProcessingLogAttachment mpla : mplAttachments) {

 

Und hier endet es auch für mich. In der BTP Integration Suite, im Message Monitor sehe ich, wie im Java-Objekt MessageProcessingLogAttachment mpla auch die Eigenschaften, also size, timestamp etc.

Das wars aber auch. Keine Payload. Die BTP bietet einen Download der Payload an. Das ist jedoch kein einfacher Link sondern Javascript und anderer Quellcode, möglicherweise sogar auf ein Token der eine begrenzte Gültigkeit hat

oder ein Einmaltoken. Da stecke ich nicht tief genug drin.

 

Es macht für mich auch kein Sinn den Quelltext der WebUI zu debuggen um dann herauszufinden dass da etwas aus der BTP übergeben wird um die Payload runterzuladen - was für mich dann völlig intransparent ist.

 

 

Lange Rede kurzer Sinn: Wenn ich mir den Screenshot oben anschaue, dann ist da ein Ordner link.

Kann ja sein das das etwas mit dem Download einer Payload zu tun hat. Steht nirgendwo! Hab ich ich vlt nur geträumt. Aber selbst wenn nicht, hier mal die Decl:

 

public class MessageProcessingLogAttachmentLink<ObjectT extends VdmObject<?> >

    extends EntityLink<MessageProcessingLogAttachmentLink<ObjectT> , MessageProcessingLogAttachment, ObjectT>

    implements MessageProcessingLogAttachmentSelectable

{

 

 

    /**

     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.

     * 

     * @param fieldName

     *     OData navigation field name. Must match the field returned by the underlying OData service.

     */

    public MessageProcessingLogAttachmentLink(final String fieldName) {

        super(fieldName);

    }

 

Ich bin ab hier total am schwimmen, zugegeben. Was ist ein Parameter fieldName? Woher nehme ich Dieses?

Selbst wenn ich da richtig bin, ich weiß nicht wo ich schauen muss. 

„Use the constants declared in each entity inner class.“. Welche? Wo?

„Instantiating directly requires knowing“ Knowing. Eben, damit bin ICH auf jeden Fall raus. Lol…

 

Any help appreciated und vielen Dank soweit auf jeden Fall mal.

Du hast ja möglicherweise noch andere „Kollegen“ die mir hier helfen könnten?

 

Meine Kontakte aus Walldorf sind ziemlich veraltet, Frank Oliver Hoffmann aus der XI-Entwicklung…ob es den noch gibt? Udo Paltzer will ich damit jetzt auch nicht unbedingt anschreiben, zumal der die Antwort auch nicht kennt.

Kathrin von Ahsen … keine Ahnung wo die mittlerweile sitzt. Du siehst, alter Hase aber leider nicht up-to-date.

 

Herzliche Grüße Jörg Hopmann

 

 

 

 

Von: Matthias Kuhr ***@***.***> 
Gesendet: Dienstag, 2. April 2024 12:06
An: SAP/cloud-sdk ***@***.***>
Cc: JHopmann ***@***.***>; Author ***@***.***>
Betreff: Re: [SAP/cloud-sdk] SAP OData client - Access MessageProcessingLogs in BTP Integration Suite- How to get (link to) attachment (Issue #1766)

 

Hi Jörg,

I'm not familiar with the specific OData service you are trying to use. In case the service metadata available on api.sap.com <https://api.sap.com/> , could you please share the link? If not, can you otherwise somehow share the metadata? Without the metadata and without knowing more about the service it's hard to know how the service is intended to be used...

The way the GUID is given in the URL in the mid of the URL "/MessageProcessingLogs"GUID"/Attachments" is - let's say - a little bit uncommon

You can check this article <https://www.odata.org/documentation/odata-version-2-0/uri-conventions/>  on how accessing entities in OData works and how it is (slightly) different from the standard REST /resource/{id}/nestedResource format.

In particular, consider reading about the meaning of $expand and how you can use it with the SAP Cloud SDK <https://sap.github.io/cloud-sdk/docs/java/features/odata/v2-vdm-client#select> . Depending on how the OData service is defined, selecting the relevant fields may solve your requirements.

**Comment by JHopmann** [comment]
Hallo Matthias,

 

Nachtrag:

 

Ich habe mein Problem gelöst, durch Zufall und herumsuchen:

 

Für die Java-Klasse MessageProcessingLogAttachment, generiert aus der API vie EDMX-Spec … da gibt es eine Methode FetchMediaStream()

Rückgabewert ist ein ByteArrayInputStream welcher die Payload eines Log-Eintrags enthält.

 

Also Lösung: Rumsuchen bis man i-was entdeckt was i-wie passt. 

 

Danke und Gruß für deine Unterstützung.

Jörg Hopmann

 

Von: Jörg Hopmann ***@***.***> 
Gesendet: Mittwoch, 3. April 2024 13:27
An: 'SAP/cloud-sdk' ***@***.***>
Betreff: AW: [SAP/cloud-sdk] SAP OData client - Access MessageProcessingLogs in BTP Integration Suite- How to get (link to) attachment (Issue #1766)

 

Hallo Matthias,

 

vielen Dank für deine Antwort. Ich habe dir parallel eine Einladung auf LinkedIn gesendet. Hoffe es trifft auf Akzeptanz so wie auch das „Du“ hoffentlich OK ist.

 

Meine Frage zu den MessageProcessingLogs zielt auf folgendes Problem ab:

Ich habe die vdm-sourcen mittels maven-generator erzeugt, aus der API-Spezifikation, die Struktur mal als Zip an diese Mail angehängt, ich hoffe das geht über github nicht verloren:

 



 

Klar das du dich da jetzt nicht tief für mich einarbeitest, aber meine Hoffnung ist das du vlt Tipps hättest.

 

Ich kann die API auf der BTP abfragen und Objekte wie z.B. 

com.sap.cloud.sdk.datamodel.namespaces.messageprocessinglogs.MessageProcessingLogAttachment

instanziieren.

 

Das geschieht wie folgt: (Ich mache es mal explizit hier, hoffe es passt):

 

List<MessageProcessingLogAttachment> mplAttachments = mpl.fetchAttachments();

   if (mplAttachments.size() > 0)  {

 

Also schauen wieviele Attachments sind drin. Mehr als 0?

Dann:

 

for (MessageProcessingLogAttachment mpla : mplAttachments) {

 

Und hier endet es auch für mich. In der BTP Integration Suite, im Message Monitor sehe ich, wie im Java-Objekt MessageProcessingLogAttachment mpla auch die Eigenschaften, also size, timestamp etc.

Das wars aber auch. Keine Payload. Die BTP bietet einen Download der Payload an. Das ist jedoch kein einfacher Link sondern Javascript und anderer Quellcode, möglicherweise sogar auf ein Token der eine begrenzte Gültigkeit hat

oder ein Einmaltoken. Da stecke ich nicht tief genug drin.

 

Es macht für mich auch kein Sinn den Quelltext der WebUI zu debuggen um dann herauszufinden dass da etwas aus der BTP übergeben wird um die Payload runterzuladen - was für mich dann völlig intransparent ist.

 

 

Lange Rede kurzer Sinn: Wenn ich mir den Screenshot oben anschaue, dann ist da ein Ordner link.

Kann ja sein das das etwas mit dem Download einer Payload zu tun hat. Steht nirgendwo! Hab ich ich vlt nur geträumt. Aber selbst wenn nicht, hier mal die Decl:

 

public class MessageProcessingLogAttachmentLink<ObjectT extends VdmObject<?> >

    extends EntityLink<MessageProcessingLogAttachmentLink<ObjectT> , MessageProcessingLogAttachment, ObjectT>

    implements MessageProcessingLogAttachmentSelectable

{

 

 

    /**

     * Use the constants declared in each entity inner class. Instantiating directly requires knowing the underlying OData field names, so use with caution.

     * 

     * @param fieldName

     *     OData navigation field name. Must match the field returned by the underlying OData service.

     */

    public MessageProcessingLogAttachmentLink(final String fieldName) {

        super(fieldName);

    }

 

Ich bin ab hier total am schwimmen, zugegeben. Was ist ein Parameter fieldName? Woher nehme ich Dieses?

Selbst wenn ich da richtig bin, ich weiß nicht wo ich schauen muss. 

„Use the constants declared in each entity inner class.“. Welche? Wo?

„Instantiating directly requires knowing“ Knowing. Eben, damit bin ICH auf jeden Fall raus. Lol…

 

Any help appreciated und vielen Dank soweit auf jeden Fall mal.

Du hast ja möglicherweise noch andere „Kollegen“ die mir hier helfen könnten?

 

Meine Kontakte aus Walldorf sind ziemlich veraltet, Frank Oliver Hoffmann aus der XI-Entwicklung…ob es den noch gibt? Udo Paltzer will ich damit jetzt auch nicht unbedingt anschreiben, zumal der die Antwort auch nicht kennt.

Kathrin von Ahsen … keine Ahnung wo die mittlerweile sitzt. Du siehst, alter Hase aber leider nicht up-to-date.

 

Herzliche Grüße Jörg Hopmann

 

 

 

 

Von: Matthias Kuhr ***@***.*** ***@***.***> > 
Gesendet: Dienstag, 2. April 2024 12:06
An: SAP/cloud-sdk ***@***.*** ***@***.***> >
Cc: JHopmann ***@***.*** ***@***.***> >; Author ***@***.*** ***@***.***> >
Betreff: Re: [SAP/cloud-sdk] SAP OData client - Access MessageProcessingLogs in BTP Integration Suite- How to get (link to) attachment (Issue #1766)

 

Hi Jörg,

I'm not familiar with the specific OData service you are trying to use. In case the service metadata available on api.sap.com <https://api.sap.com/> , could you please share the link? If not, can you otherwise somehow share the metadata? Without the metadata and without knowing more about the service it's hard to know how the service is intended to be used...

The way the GUID is given in the URL in the mid of the URL "/MessageProcessingLogs"GUID"/Attachments" is - let's say - a little bit uncommon

You can check this article <https://www.odata.org/documentation/odata-version-2-0/uri-conventions/>  on how accessing entities in OData works and how it is (slightly) different from the standard REST /resource/{id}/nestedResource format.

In particular, consider reading about the meaning of $expand and how you can use it with the SAP Cloud SDK <https://sap.github.io/cloud-sdk/docs/java/features/odata/v2-vdm-client#select> . Depending on how the OData service is defined, selecting the relevant fields may solve your requirements.

**Comment by MatKuhr** [comment]
@JHopmann I deleted your comments because they contained some personal/private information/messages. Please remember that when responding here or via email you are posting to a public GitHub issue 😉 

I'm glad that you eventually were able to find the correct fields and API endpoints. 

In general, the OData generator provided by the Cloud SDK is meant to make using OData APIs easier. With the generated code you can explore the API in your IDE (like in [this gif](https://sap.github.io/cloud-sdk/docs/java/overview-cloud-sdk-for-java#odata-and-openapi)) and don't have to read through the EDMX XML files. Still, you have to know the semantics and structure of the specific API and thus have to consult the relevant documentation for the specific service you want to use. 

In case you have any other questions on how to use the Cloud SDK feel free to open another issue.
