### ISSUE TITLE
Trailing slashes

### ISSUE THREAD

**Issue by ant2012** [SAP/cloud-sdk#190]
The version of the library is
```
<dependency>
    <groupId>com.sap.cloud.sdk.datamodel</groupId>
    <artifactId>odata-core</artifactId>
    <version>3.39.0</version>
</dependency>
```

## Issue Description
1. I use generated strongly typed Java client against an OData V2 SAP service.
2. The service is build upon some SAP CDS view and it requires the url segment to ends with the trailing slash
e.g. from the Postman
https://host/servise-path/resource-path/?$filter...  - is working
https://host/servise-path/resource-path?$filter..  - is not

3. It is not option for me to change the service behavior

4. The class from SDK
com.sap.cloud.sdk.datamodel.odata.client.request.ODataUriFactory
always provide an URL without trailing slash and it seems there are no possibilities to change this with any overrides or factory static parameters.

5. If I add trailing slash to the end of entity collection name in the generated default service, it will be url-encoded in method
ODataResourcePath.toEncodedPathString
to "%2F"
and the service will reject it too.
https://host/servise-path/resource-path%2F?$filter..  - not working

So, the question is:
Is there a way to force SDK to generate URLs with trailing slashes?
like this
https://host/servise-path/resource-path/?$filter...

**Comment by Johannes-Schneider** [comment]
Hi @ant2012,

thank you for reaching out to us.
What you are observing is indeed intended behavior - we consider omitting the trailing slash as a best-practice.
This approach is also working for a vast majority of services.

To overcome your issue, I suggest using our [Generic OData Client](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client) like so:

```Java
ODataRequestRead request = new ODataRequestRead("/service-path", "resource-path/", "$filter=...", ODataProtocol.V2)
// produces an URI like this: /service-path/resource-path/?$filter=...

HttpClient client = HttpClientAccessor.getHttpClient(destination);
ODataRequestResultGeneric result = request.execute(client);
```

Best regards
Johannes

**Comment by artemkovalyov** [comment]
Hey @ant2012 ,

Has the solution worked for you? I created a docs PR to add this workaround for future reference: https://github.com/SAP/cloud-sdk/pull/200

I'll be closing this issue. Don't hesitate to re-open it if you still have questions or the proposed solution doesn't fit your use-case.

Take care!

**Comment by artemkovalyov** [comment]
@ant2012, I'll re-open this as we also decided to provide an API to handle both service URI versions. We'll keep you posted when the API is released. In the meanwhile, you can use a generic client as a workaround mentioned in my previous comment.

**Comment by ant2012** [comment]
Hey, Artem.
Thank you for your support.
I have to mention one more related stuff then.
I think it can be useful for me and other LIB's users.
Please also pay attention to autogenerated GET for the CSRF token retrieval.
When I invoke some POST to some entity collection, the LIB always genarates prepending GET against the root of the corresponding service - and also always wo the trailing slash.

**Comment by artemkovalyov** [comment]
Hey @ant2012, that's a good catch. I added this to the acceptance criteria of this feature.

@newtork, @Johannes-Schneider, do we still always use GET for fetching CSRF instead of HEAD for the pre-flight in the generator?

**Comment by ant2012** [comment]
Hey, guys.
No, sorry, it was my mistake. The lib currently implemented with HEAD indeed.

**Comment by artemkovalyov** [comment]
@ant2012, I'll be closing this as we don't see many complaints coming towards this issue and won't have hands to work on this in the nearest time. Most of the services seem to interoperate well with the SDK. Custom ones may, indeed, have some compatibility issues. We'll consider adding more flexibility in the future if the problem reveals itself more.
Our Generic OData Client should still be of help as suggested by Johannes.
