### ISSUE TITLE
SDK util setLogLevel seems to do nothing

### ISSUE THREAD

**Issue by MatCob** [SAP/cloud-sdk#194]
**Describe the bug**
I'm creating a NodeJS application on Cloud Foundry and I am noticing a lot of warning & info messages in the log.

While browsing through the API page of the [@sap/cloud-sdk-util](https://help.sap.com/doc/7f30fcdb8c424be9b1d4ecbfd7dd972f/1.0/en-US/modules/_sap_cloud_sdk_util.html#setloglevel) package I found the setLogLevel method which I thought would do exactly what I need/want. But after some fiddling around with it I can't get it to remove the warnings in the log.

I have quickly set up a [public repo](https://github.com/MatCob/SDKLogLevelTest) to show my code. I removed some files for generating the odata client files. 

**To Reproduce**
1. use the SetLogLevel method of the SDK util package
2. Check the logs on Cloud Foundry 
3. See a lot of info and warning messages in the log

**Expected behavior**
Expected to only see errors in the log

**Screenshots**
The log on CF:
![image](https://user-images.githubusercontent.com/22294540/84736578-6a3c7380-afa6-11ea-9c30-6502b0d83d9c.png)

A screenshot of my code:
![image](https://user-images.githubusercontent.com/22294540/84736725-cb644700-afa6-11ea-8011-5432397c3b2b.png)

**Used Versions:**
 - node v10.19.0
 - npm v6.13.4
 - SAP Cloud SDK v1.17.2

**Code Examples**
See public repo above

**Please check the following points**
- [X] Have you provided detailed description about your issue?
- [X] Have you shared all the necessary information to help the cloud-sdk developer reproduce the issue?
- [X] Have you provided the expected behaviour?
- [X] Have you attached some useful screenshots?
- [X] Have you provided the node/npm/cloud-sdk versions?
- [X] Have you shared your code snippets as a minial example?
- [ ] Have you provided you log file or related error messages?
- [X] Have you searched for related issues on [Stackoverflow]
Link to answers.sap.com issue: [https://answers.sap.com/questions/13068848/setloglevel-on-sap-cloud-sdk-logger.html?childToView=13070715#comment-13070715](https://answers.sap.com/questions/13068848/setloglevel-on-sap-cloud-sdk-logger.html?childToView=13070715#comment-13070715)

**Comment by mr-flannery** [comment]
Thanks for raising this issue! While we're still going to investigate this, of course, have you checked whether upgrading the version solves the problem? Note, that since the move to open source, the package names changed from `@sap/cloud-sdk-core` to `@sap-cloud-sdk/core` (same for the other non-VDM packages).

**Comment by MatCob** [comment]
I upgraded to the open source packages and the problem is indeed resolved now. Wonderful! I will inform the other members in my team to use these from now on.

**Comment by artemkovalyov** [comment]
Happy to hear it, @MatCob. I'd recommend keeping SDK up to date at all times. We usually release on a bi-weekly basis and try to stay off breaking changes or we explicitly mention them in release notes.

Can we help you with anything else or this issue can be closed?

**Comment by MatCob** [comment]
This issue can be closed. Thanks for the quick response and keep up the good work!
