### ISSUE TITLE
Error while creating a project with sap-cloud-sdk init 

### ISSUE THREAD

**Issue by gopalanand333** [SAP/cloud-sdk#208]
I'm trying to initialize a project with sap-cloud-sdk init <project-name> 
It's giving the following error: 
>sap-cloud-sdk init test
The target directory (test) does not contain a `package.json.`
Should a new `nest.js` project be initialized in the target directory? (y|n): y
Building application scaffold... !
 »   Error: Command failed with exit code 1: npx -p @nestjs/cli nest new . --skip-install --package-manager npm

**To Reproduce**
sap-cloud-sdk init test

**Expected behavior**
It should create a project template

**Used Versions:**
 @sap-cloud-sdk/cli/0.1.9 win32-x64 node-v12.16.1

**Comment by marikaner** [comment]
Hello @gopalanand333,

there is a repository specifically for the cli: https://github.com/SAP/cloud-sdk-cli. It would be great if you could open this issue there (in case other people encounter the same problems).
Anyways, it seems that the command fails when building the application scaffold of nestjs. Can you please run `npx -p @nestjs/cli nest new . --skip-install --package-manager npm` directly and share the output here?

**Comment by gopalanand333** [comment]
Hi @marikaner ,
here's the output: 
 npx -p @nestjs/cli nest new . --skip-install --package-manager npm
npm ERR! Unexpected end of JSON input while parsing near '...ersion: OpenPGP.js v3'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\******\AppData\Roaming\npm-cache\_logs\2020-06-24T06_55_48_655Z-debug.log
Install for [ '@nestjs/cli@latest' ] failed with code 1



I have uploaded the log too. 
I will open a ticket in cloud-sdk-cli. Thanks for the information. 
[log.txt](https://github.com/SAP/cloud-sdk/files/4823669/log.txt)

**Comment by marikaner** [comment]
Moved to https://github.com/SAP/cloud-sdk-cli/issues/71
