### ISSUE TITLE
Changing log format doesn't work

### ISSUE THREAD

**Issue by simfer** [SAP/cloud-sdk#215]
I’ve created a new project from scratch using the SAP Cloud SDK archetype. In the project the logback.xml file is configured as this:
![01](https://user-images.githubusercontent.com/6877529/85828458-c3678c80-b788-11ea-9497-ff9cbb638517.png)
If I run the project I see the following log:
![02](https://user-images.githubusercontent.com/6877529/85828490-d8dcb680-b788-11ea-9e02-6e8e5fea577a.png)
Now I would like to change the log format and for this reason I slightly modified the logback.xml file as this:
![03](https://user-images.githubusercontent.com/6877529/85828540-f27dfe00-b788-11ea-87c8-01ee2ce698bd.png)
Unfortunately, running the app again I still see the same log. It seems that the logback.xml file is not taken into account.
![04](https://user-images.githubusercontent.com/6877529/85828599-104b6300-b789-11ea-87dc-66f273116a4d.png)
Is there anything missing?
Simmaco

**Comment by marikaner** [comment]
Hey @simfer,

this repository is for the SAP Cloud SDK for JavaScript. Sorry for the confusion. For issues in the SAP Cloud SDK for Java I recommend to open an issue on [StackOverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk+java).

I will close this for now.
