### ISSUE TITLE
Link the API documentation directly in the footer

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk#296]
Hello SAP Cloud SDK Team,

I think it would be helpful to have a link to the current API documentation available in the footer. For Javascript the link should point to https://sap.github.io/cloud-sdk/api/1.41.0/index.html. The configuration for this would need to be done in [docusaurus.config.js#L123](https://github.com/SAP/cloud-sdk/blob/main/docusaurus.config.js#L123).

Best Regards
Gregor

**Comment by artemkovalyov** [comment]
Hi @gregorwolf,

Footer is a bit complicated and I'm not sure it's very discoverable there. I'll ask the team to add it to our [release notes](https://github.com/SAP/cloud-sdk-js/releases) on the repository. You can quickly access release notes from the top menu bar on the documentation portal.

Thanks for the feedback and suggestion!

Best,
Artem
