### ISSUE TITLE
Possible GPL-3.0 compliance issue

### ISSUE THREAD

**Issue by prabhu** [SAP/cloud-sdk#305]
**Describe the bug**
I am not an expert in software licenses. I'm just a tool author. I scanned this repo using [ShiftLeft Scan](https://slscan.io) and it has identified possible license compliance issue with this repo which I am sharing here.

This repo uses madge as a dev dependency. madge uses graphviz as a direct dependency.

graphviz is currently published as GPL-3.0 in npmjs. In the source code, the author has tried to clarify and change the license to MIT but forgot to re-publish the package under MIT.
https://github.com/glejeune/node-graphviz/commit/ca6394b7227aa35f3b1170991827114b00a9bcbd

The graphviz continues to use GPL-2.0 and later in some headers such as https://github.com/glejeune/node-graphviz/blob/master/lib/ext/gvpr/dot2js.g

As it stands, there is a lack of clarity regards to the exact license of graphviz. Due to the transitive nature of [GPL](https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL), the exact license of cloud-sdk and therefore all apps using the sdk is unclear atm.

Please consider workarounds to help address this concern.

**Comment by marikaner** [comment]
Hello @prabhu,

thanks a lot for reporting this. I just investigated this a bit, but will discuss it internally. I personally think that this should not lead to any compliance issues for us, because I understand that our license is compatible with GPL-3.0. I don't know whether comments  as the example you gave are even legally relevant.
As the graphviz dependency currently only comes in as a transitive dependency of a dev dependency (madge), I believe we are on the safe side here.

Anyways, I will discuss the necessity of a workaround in the team and will let you know.

**Comment by artemkovalyov** [comment]
Hey @prabhu ,

Many thanks for the heads up and for bringing this to our attention. After checking a bit deeper it seems that if we only use the software but not link and distribute our product with this software as a dependency we are not affected with an underlying license.

We'll be consulting further regarding this to make sure we're compliant. May I also ask what served the purpose to scan the repo? 

Best,
Artem

**Comment by prabhu** [comment]
Thanks @artemkovalyov for the clarification. Please keep the issue open till we have a definite response since if this repo becomes GPL-3.0 then by definition all your customer apps using the SDK could also become GPL-3.0!

As to regarding the purpose, ShiftLeft is a code analysis company. [Scan](https://slscan.io) is a free open-source version that can be used to analyze repos for security, dependency and license issues. The compliance issue highlighted by scan was brought to my attention for clarification. Hope this helps.

**Comment by marikaner** [comment]
Hey @prabhu,

As @artemkovalyov pointed out, the dependency in question is not shipped with the SDK. In addition, according to [this list](http://gplv3.fsf.org/wiki/index.php/Compatible_licenses) GPLv3 is compatible with Apache 2.0.

**Comment by prabhu** [comment]
Compatibility is from a less copyleft license to a strong copyleft license.

Apache 2 software can therefore be included in GPLv3 projects, because the GPLv3 license accepts our software into GPLv3 works. However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

https://www.apache.org/licenses/GPL-compatibility.html

**Comment by artemkovalyov** [comment]
Thanks, @prabhu, this makes sense. We started a case internally to verify licensing compliance from the legal perspective even despite we don't ship any GPLx licensed dependencies with our OS code. It might take some time for the committee. For that reason, we'll keep the case open to get you updated on our decision.

**Comment by marikaner** [comment]
@prabhu According to our internal investigation there is no action needed from our side! Thanks for reporting this!
