### ISSUE TITLE
Explain how to use the SDK function mockDestinationsEnv()

### ISSUE THREAD

**Issue by PierreFritsch** [SAP/cloud-sdk#31]
>  The SDK provides a mockDestinationsEnv(...destinations) method which takes a list of destination objects, transforms it to a JSON array and assigns it to the process.env.destinations.

https://sap.github.io/cloud-s4-sdk-book/pages/mock-odata.html

Adding a code sample would be helpful. If the function is meant to be called out of node.js or TypeScript modules, adding the corresponding `import` statement would help understand where this function is located.

The current wording of the documentation leads me to try to run the following command on the command line:

    $ sap-cloud-sdk mockDestinationsEnv

... which returns this error message:

    ›   Warning: mockDestinationsEnv is not a sap-cloud-sdk command.
    Did you mean version? [y/n]:

**Comment by artemkovalyov** [comment]
Hi, @PierreFritsch 

Is this related to your PR that has already been merged? If so, can I close it then?

**Comment by pierri** [comment]
Hi @artemkovalyov 

Yes, it is related, but no, it is not solved with the PR you mentioned.

It would be helpful if the code example could be extended to explain how to access mockDestinationsEnv

**Comment by FrankEssenberger** [comment]
This is the mentioned PR: https://github.com/SAP/cloud-sdk/pull/30.
