### ISSUE TITLE
Build badge for JavaScript points to documentation instead of code repository

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk#323]
On the start page of the documentation at https://sap.github.io/cloud-sdk/ there is a Badge showing the Build status of the SAP Cloud SDK for JavaScript it is currently pointing to the documentation repository (https://github.com/SAP/cloud-sdk) instead of https://github.com/SAP/cloud-sdk-js

**Comment by artemkovalyov** [comment]
Hi @gregorwolf, thank you for the good hint! The docs repo used to be an SDK repo half a year ago and we forgot to change the badge. We'll certainly update it.

**Comment by artemkovalyov** [comment]
Hi @gregorwolf, thanks again for the hint. Fixed by this PR: https://github.com/SAP/cloud-sdk/pull/325
