### ISSUE TITLE
Generator: TypeScript error for required properties in complex types

### ISSUE THREAD

**Issue by ja-ne** [SAP/cloud-sdk#341]
**Description**
Complex types with non-nullable properties seem to lead to TypeScript type errors when working with the @sap-cloud-sdk/generator version 1.25.0. This did not occur with version 1.24.0.

**To Reproduce**
1. Get the EDMX-specification for the Attachments ODATA API from SAP S/4HANA Cloud Package: [https://api.sap.com/api/API_CV_ATTACHMENT_SRV/overview](https://api.sap.com/api/API_CV_ATTACHMENT_SRV/overview).
2. Generate a service module from this specification using the @sap-cloud-sdk/generator version 1.25.0. You can, for instance, follow [these steps](https://github.com/SAP/cloud-sdk/blob/master/packages/generator/README.md) or [this introduction](https://developers.sap.com/tutorials/cloudsdk-js-generator.html).
`generate-odata-client --inputDir specifications --outputDir generator-modules`
3. Use the generated TypeScript service module in a TypeScript project (e.g. import it in a file index.ts):
`import * as attachmentService from './generator-modules/cv-attachment-service';`

4. Transpile the project code to JavaScript.
`tsc index.ts`
5. Result: There is an error message indicating missing required properties.
![grafik](https://user-images.githubusercontent.com/49640230/88919706-e1cf1500-d26b-11ea-9ae5-0795208fb6db.png)
These steps work for other specification files containing complex types with required properties as well.

**Expected behavior**
The service module should transpile without errors. 

**Used Versions:**
 - node version: 10.19.0
 - npm version: 6.14.1
 - SAP Cloud SDK: 1.25.0
 - TypeScript: 3.9.6

Did I miss something? Is there a workaround?

Many thanks in advance and best regards,
ja-ne

**Comment by marikaner** [comment]
Hey @ja-ne,

thank you for reporting this. We will take a look at this. In the mean time I would be interested whether there is a reason for you to generate the S4Hana VDM on your own? Are you aware of the [@sap/cloud-sdk-vdm-attachement-service module](https://www.npmjs.com/package/@sap/cloud-sdk-vdm-attachment-service)? This might be a suitable workaround for you.

**Comment by ja-ne** [comment]
Hello @marikaner ,
thanks for the quick response. I have several generated service modules and merely chose the attachment service as simple (but, as it turns out, unsuitable) example.

**Comment by marikaner** [comment]
Hey @ja-ne,

we have found and solved the issue, a new version will be available with the next release.

**Comment by marikaner** [comment]
Fixed with version 1.26.0. Please try again and let us know if there are any further issues.

**Comment by ja-ne** [comment]
Thanks for the fix, everything works fine now.
