### ISSUE TITLE
Bug with a generated service containing the "Moment" import

### ISSUE THREAD

**Issue by CharlesDuboisSAP** [SAP/cloud-sdk#365]
**Describe the bug**
There is a problem with a generated service containing the "Moment" import

**To Reproduce**
```sh
git clone https://github.com/CharlesDuboisSAP/cloud-sdk-team-calendar.git
git pull origin fix
git chekout fix
npm install
````
place the [time-off edmx](https://api.sap.com/api/ECTimeOff/overview) in the generator-input folder

```sh
npm run generate
```

open `src\generated\ec-time-off-service\HolidayAssignmentRequestBuilder.ts`

**Expected behavior**
no errors inside my generated service

**Screenshots**

the problematic file
![image](https://user-images.githubusercontent.com/66725443/89546100-799ca800-d804-11ea-87ff-0a904e2839e3.png)

the error
![image](https://user-images.githubusercontent.com/66725443/89546249-aa7cdd00-d804-11ea-952b-435bd30cf0c4.png)

GetByKeyRequestBuilder anf FieldType
![image](https://user-images.githubusercontent.com/66725443/89546391-d8fab800-d804-11ea-9584-0bae8cb9c037.png)

**Used Versions:**
 - node version v12.18.0
 - npm version 6.14.4
 - SAP Cloud SDK version 1.26.1

everything but cds stuff was updated:
```
 @sap/cds                                          ^3.13.0  →   ^4.1.5 
 @sap/cds-services                                  1.14.0  →   1.27.1 
 @sap-cloud-sdk/core                               ^1.18.0  →  ^1.26.1
 @sap/cloud-sdk-vdm-workforce-timesheet-service    ^1.18.0  →  ^1.19.2
 @sap/hdi-deploy                                     3.7.x  →   3.11.x
 express                                           ^4.16.4  →  ^4.17.1
 hdb                                               ^0.17.0  →  ^0.18.1
 ts-node                                            ^8.0.3  →  ^8.10.2
 typescript                                      ^3.3.4000  →   ^3.9.7
 @sap-cloud-sdk/generator                          ^1.18.0  →  ^1.26.1
 @types/chai                                        ^4.2.0  →  ^4.2.12
 @types/express                                    ^4.16.1  →  ^4.17.7
 @types/mocha                                       ^5.2.6  →   ^8.0.1
 @types/sinon                                      ^7.0.13  →   ^9.0.4
 @types/sinon-chai                                  ^3.2.3  →   ^3.2.4
 chai-http                                          ^4.2.1  →   ^4.3.0
 dotenv                                             ^8.0.0  →   ^8.2.0
 js-yaml                                           ^3.13.0  →  ^3.14.0
 mocha                                              ^5.2.0  →   ^8.1.1
 mocha-junit-reporter                              ^1.18.0  →   ^2.0.0
 node-mocks-http                                    ^1.7.3  →   ^1.8.1
 nodemon                                          ^1.18.10  →   ^2.0.4
 nyc                                               ^15.0.0  →  ^15.1.0
 sinon                                              ^7.4.1  →   ^9.0.2
 sinon-chai                                         ^3.3.0  →   ^3.5.0
 sqlite3                                            ^4.0.7  →   ^5.0.0
```

**Log file**
```sh
± |fix U:2 ?:3 ✗| → npm run ci-build
> cloud-sdk-timesheet-app@1.0.0 ci-build /home/i531196/dev/tmp/cloud-sdk-team-calendar
> npx tsc && npm run cds-deploy:local && cp -r src/app db srv dist/
src/generated/ec-time-off-service/HolidayAssignmentRequestBuilder.ts:23:7 - error TS2322: Type 'Moment' is not assignable to type 'FieldType'.
  Property 'isoWeeksInISOWeekYear' is missing in type 'import("/home/i531196/dev/tmp/cloud-sdk-team-calendar/node_modules/moment/moment").Moment' but required in type 'moment.Moment'.
23       date: date
         ~~~~
  node_modules/@sap-cloud-sdk/core/node_modules/moment/ts3.1-typings/moment.d.ts:549:5
    549     isoWeeksInISOWeekYear(): number;
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'isoWeeksInISOWeekYear' is declared here.
  node_modules/@sap-cloud-sdk/core/node_modules/@sap-cloud-sdk/util/dist/types.d.ts:5:5
    5     [key: string]: T;
          ~~~~~~~~~~~~~~~~~
    The expected type comes from this index signature.
Found 1 error.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! cloud-sdk-timesheet-app@1.0.0 ci-build: `npx tsc && npm run cds-deploy:local && cp -r src/app db srv dist/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the cloud-sdk-timesheet-app@1.0.0 ci-build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/i531196/.npm/_logs/2020-08-06T13_50_55_727Z-debug.log
````

**Please check the following points**
- [x] Have you provided detailed description about your issue?
- [x] Have you shared all the necessary information to help the cloud-sdk developer reproduce the issue?
- [x] Have you provided the expected behaviour?
- [x] Have you attached some useful screenshots?
- [x] Have you provided the node/npm/cloud-sdk versions?
- [x] Have you shared your code snippets as a minial example?
- [x] Have you provided you log file or related error messages?
- [x] Have you searched for related issues on [Stackoverflow](https://stackoverflow.com/questions/tagged/sap-cloud-sdk) or [answers.sap.com](https://answers.sap.com/tags/73555000100800000895)?

**Comment by FrankEssenberger** [comment]
I have checked with our test entities and also generating the ECTimeOff API and ther eis no error. I assume that some dependency in the project fixes the moment version to something which is not in line with the version ~2.27.0 defined by the SDK core.

**Comment by FrankEssenberger** [comment]
So I was able to reproduce the issue - but I had to do some work. The origin is a new field called: `isoWeeksInISOWeekYear`.
This is prensent in version 2.27.0 but not in version 2.24.0 of moment:

![image](https://user-images.githubusercontent.com/56544999/89665586-37916600-d8d9-11ea-9730-210e60d19d94.png)

Where to these two versions of moment come from:
- @sap/cds-runtime 1.2.2 -> sdk-core 1.18.1  (fixed version, this is not good)
- sdk-core 1.18.1 -> moment:"2.24.0" (fixed version, this is not good)
- sdk-core 1.26.1 -> moment:"^2.27.0" 

So we have the two versions of moment flying around. However, for me the version 2.27.0 ended up in the node_modules/moment. I needed to manually `npm i moment@2.24.0` so that I got the version 2.24.0 in the root /node_modules.

So as a work around you could try to instal moment version 2.27.0. I have to understand how `npm` resolved the version of a dependency in case two conflicting version are declared. I would have hoped that the new version wins, but this seem not to be the case.

**Comment by FrankEssenberger** [comment]
Or could you please try to move the sdk-core up in the list of dependencies in the package.json:
```
"dependencies": {
    "@sap-cloud-sdk/core": "^1.26.1", //this is top
    "@sap/cds": "^3.34.2",
    "@sap/cds-services": "1.14.0",
    "@sap/cds-dk": "^1.8.1",
...
```
Perhaps npm does a first come first servce approach. And when the new sdk-core is on top also the new moment should go on top.

**Comment by FrankEssenberger** [comment]
Due to the missmatching versions of moment and the fixed moment version I guess this is the way it is. The installation of the latest moment on the root works as a work around and I hope the cds-runtime colleagues do update to a more recent SDK version or even better also used flexible versions.
