### ISSUE TITLE
No Release Notes for version 3.49.0 online on the SDK website

### ISSUE THREAD

**Issue by wlsc** [SAP/cloud-sdk#368]
No Release Notes for version 3.49.0 online on website
https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java/

**Comment by Johannes-Schneider** [comment]
Hi @wlsc,

release `3.49.0` is scheduled to be publicly available by next week (we perform releases every two weeks only).
Internal users get access to our releases one week earlier, but our release notes will be updated only when the version is available for all consumers.

Best regards,
Johannes

**Comment by wlsc** [comment]
@Johannes-Schneider thanks for the prompt reply. Now it clear why 😅
