### ISSUE TITLE
How to do deep insert function with Cloud SDK (Upsert / Batch)

### ISSUE THREAD

**Issue by phangkw** [SAP/cloud-sdk#407]
Hi Expert, 

    I have a requirement to create a Success Factor extension with SAP UI5 (frontend) + nodejs (middleware) + SF api (data model). 
    After we have spoken to SAP expert, to ease all the necessary steps to perform "Principle Propogation" with beare token call from Success Factor -> Sap Cloud Platform (Cloud Foundry) -> Propagate to RESTFUL services (via api call) hosted in CF, the authorisation is called via Success Factor => SAP IAS server. 

   What I have done is to download the OData definition (EDMX file) from API Hub and generated the functions via the npx generate-odata-client --inputDir service-specs --outputDir generated --forceOverwrite command. The system is generated correctly. 

   We are currently able to follow most of the tutorial from https://sap.github.io/cloud-sdk/docs/js/features/odata/overview for both "C" - Post, "R" - Get, "U" - Put and "D" - Delete accordingly. But when we tried to follow the example given in the blog for Batch Requests# ( retrieve requests and changesets ) , we are not able to follow as the batch and changeset function is not defined in our generated class. Can you kindly advice is there anywhere which we can do "UPSERT" or "BATCH" function using SDK ? and if you can provide some example, it will be great help.

Example of batch and changeset for businessPartnerAddress (sample) but this is not generated as part of the npx generate command.

updateAddresses(businessPartnerAddresses: BusinessPartnerAddress[])
:Promise<BusinessPartnerAddress[]> {
  const updateRequests = businessPartnerAddresses.map(
    address => BusinessPartnerAddress
      .requestBuilder()
      .update(address)
  );

  const [updateChangesetResponse] = await batch(changeset(...updateRequests))
    .execute(destination);

  return (updateChangesetResponse as WriteResponses)
    .responses
    .map(
      response => response.as(BusinessPartnerAddress)
    );
}

**Comment by FrankEssenberger** [comment]
Hello phangkw ,

I will have a look at the edmx file as soon I find some time. Regarding the http client you would call it like this:

```
const destination = {
   destinationName: <yourDestinationName>,
   jwt: <yourJwtToken>
}//You can also give the destination object directly here. But the lookup is more convinient.
const config = {
     method: HttpMethod.GET,
     params: {
          a: 'a',
          b: 'b'
     }
};

const response = await executeHttpRequest(destination, config);
```

Best
Frank

**Comment by phangkw** [comment]
> Hello phangkw ,
> 
> I will have a look at the edmx file as soon I find some time. Regarding the http client you would call it like this:
> 
> ```
> const destination = {
>    destinationName: <yourDestinationName>,
>    jwt: <yourJwtToken>
> }//You can also give the destination object directly here. But the lookup is more convinient.
> const config = {
>      method: HttpMethod.GET,
>      params: {
>           a: 'a',
>           b: 'b'
>      }
> };
> 
> const response = await executeHttpRequest(destination, config);
> ```
> 
> Best
> Frank

=================================================================================

Hi Frank, thank you very much. Managed to perform the API call as per the explanation. 
Just added my codes as below just incase others people encountering the same issues as I struggle in the past 2 weeks. =).  
<the code might not be the best but it works !>

=================================================================================
//Adding the libraries from the sap cloud sdk/core.
const {
    retrieveJwt, executeHttpRequest, HttpMethod
} = require("@sap-cloud-sdk/core");


exports.<FunctionName>= function (req, res) {

 const destination = {
        destinationName: <API configured in Cloud Foundry>
        jwt: retrieveJwt(req) //just incase u need to pass by JWT token 
        }
//You can also give the destination object directly here. But the lookup is more convinient.
    const config = {
        method: HttpMethod.GET,
        url: '/odata/v2/getUsersByDynamicGroup',
        params: { // pass in the query parameters 
            groupId: process.env.hradmin
        }
    };

//Used Promise instead of await / sync. it just work vice versa.
    return new Promise((resolve, reject)=>{

        executeHttpRequest(destination, config)
        //axios.get('https://api.github.com/users/mapbox')
        .then((response) => {
            resolve(response.data);
        });
    });
}
}

**Comment by FrankEssenberger** [comment]
Good that we have a working solution for the moment. We will also add some code example and information in our docu page:
https://sap.github.io/cloud-sdk/.

**Comment by FrankEssenberger** [comment]
In order to close the issue I also looked at the client generated by the VDM. As I expected the `upsert` is not represented and support would be tricky. So in this case use the work around I mentioned. For batch I see in the `BatchRequest.ts` or typescript analogon. With this you can do batch request as described in the tutorial mentioned above with something like:

```
  const updateRequests = businessPartnerAddresses.map(address => BusinessPartnerAddress.requestBuilder().update(address));

  const [updateChangesetResponse] = await batch(changeset(...updateRequests)).execute({
    url: 'https://my.s4hana.ondemand.com/'
  });
```

Best Frank
