### ISSUE TITLE
How do you do Dynamic Filter using SAP Cloud SDK

### ISSUE THREAD

**Issue by phangkw** [SAP/cloud-sdk#408]
I have a requirement to create a Success Factor extension with SAP UI5 (frontend) + nodejs (middleware) + SF api (data model). 

We are currently using the SAP Cloud SDK to construct all the queries by submitting requestBuilder().getAll(); There is a requirement which we need to build to perform filter dynamically according to the parameters passed in from the body, we can't use pre-defined selection. Can you kindly advice how can we do it ? Can we use customQueryString to do this ? If yes, can you advice how can we use to build "Or" and "And" condition for the filter ?

Sample Code : 
 const cust_TransportHeaderRequestBuilder = Cust_TransportHeader.requestBuilder().getAll();
    cust_TransportHeaderRequestBuilder.filter(
        //Claim Date, Claim Receipt No, Claim Status
        // Cust_BenefitClaims.CUST_RECEIPT_DATE.equals(moment(req.query.cust_ReceiptDate)),
        Cust_TransportHeader.EXTERNAL_CODE.equals(ExternalCode),
        Cust_TransportHeader.CUST_CLAIM_STATUS.notEquals("Rejected"),
        Cust_TransportHeader.CUST_CLAIM_STATUS.notEquals("Draft"),

        // Cust_BenefitClaims.CUST_RECEIPT_NO.equals(moment(req.query.cust_ReceiptNo)),
    )

Method Tried : 
*The predefine method works like a champ

    cust_PtfMainRequestBuilder.filter(
         new Filter("cust_ClaimStatus", "ne", "Rejected"),
         new Filter("cust_ClaimStatus", "ne", "Draft")
    )

But when I tried to construct it dynamically, it's not taking in array but rather than argument. 

filterArray = []; 
filterArray.push(new Filter("cust_ClaimStatus", "ne", "Rejected");
filterArray.push(new Filter("cust_ClaimStatus", "ne", "Draft");

* This will failed. 
    cust_PtfMainRequestBuilder.filter(filterArray);

**Comment by FrankEssenberger** [comment]
The second version should work. The error seems to be typescript related.

 Do you use a recent TS version? Do you use "target: es5" in your tsconfig.json? I have just tested the method 2 locally and it gives me a proper OData query string without errors.

**Comment by phangkw** [comment]
> The second version should work. The error seems to be typescript related.
> 
> Do you use a recent TS version? Do you use "target: es5" in your tsconfig.json? I have just tested the method 2 locally and it gives me a proper OData query string without errors.

I think I know what is the problem, I'm not using Type Script (TS) but rather just regular (JS), that might be the differences. Any idea how can i construct the dynamic value via normal javascript ?

**Comment by FrankEssenberger** [comment]
hm, if you are not using typescript I do not get the errors and also the `...` is not needed. I just compiled my TypeScript test to JS and got the following:
```
var filter_1 = require("../src/odata/common/filter");
var test_service_1 = require("./test-util/test-services/v4/test-service");

var filters = [test_service_1.TestEntity.STRING_PROPERTY.equals('ABC'), test_service_1.TestEntity.BOOLEAN_PROPERTY.equals(true)];
var getAll = test_service_1.TestEntity.requestBuilder().getAll().filter(filter_1.and(filters));
console.log(JSON.stringify(getAll.requestConfig.filter));
```
The console output should be:
```JSON
{"andFilters":[{"andFilters":[[{"field":"StringProperty","operator":"eq","value":"ABC","edmType":"Edm.String","_fieldName":"StringProperty"},{"field":"BooleanProperty","operator":"eq","value":true,"edmType":"Edm.Boolean","_fieldName":"BooleanProperty"}]],"orFilters":[]}],"orFilters":[]}
```

**Comment by FrankEssenberger** [comment]
Note that the imports are different of course for you:

```
var core = require("@sap-cloud-sdk/core");
var filters = ...
core.and(filters)
```

**Comment by phangkw** [comment]
Hi Frank,   

   Sorry to disturb you again. I have tried on the approach and it's giving me other issues. I notice if we do it through the method you mentioned, the system will append more structure in comparison if we i just add into filter as previously.

New Code : Use the code with Array.
========================================================================
var core = require("@sap-cloud-sdk/core");
var filters = [Cust_EntitlementBenefitPlanMain.EXTERNAL_CODE.equals("70000001"), Cust_EntitlementBenefitPlanMain.EXTERNAL_CODE.equals("70000002")];
    // Will need to create benefit filter dynamically based on the relevant benefit plans. 

    cust_EntitlementBenefitPlanMain.filter(core.or(filters));
    
    console.log(JSON.stringify(cust_EntitlementBenefitPlanMain.requestConfig.filter));

    if (process.env.env != "DEV") {
        return cust_EntitlementBenefitPlanMain.execute({
            destinationName: process.env.apiDest,
            jwt: retrieveJwt(req)
        });
    } else {
        return cust_EntitlementBenefitPlanMain.execute({
            destinationName: process.env.apiDestBasic,
        });
    }
}
=========================================================================
The system is giving me this error ;

Could not construct query parameters from filter. Filter is not valid: [object Object],[object Object]

The objects in console logs are following : 
{"andFilters":[{"andFilters":[],"orFilters":[[{"field":"externalCode","operator":"eq","value":"70000001","edmType":"Edm.String","_fieldName":"externalCode"},{"field":"externalCode","operator":"eq","value":"70000002","edmType":"Edm.String","_fieldName":"externalCode"}]]}],"orFilters":[]}


Existing Code : Fixed filter 
==========================================================================
        cust_EntitlementBenefitPlanMain.filter(or(Cust_EntitlementBenefitPlanMain.EXTERNAL_CODE.equals(utilsCommon.get_externalid(res, req, "externalid")),
                Cust_EntitlementBenefitPlanMain.EXTERNAL_CODE.equals("70000002"),
            ));

            console.log(JSON.stringify(cust_EntitlementBenefitPlanMain.requestConfig.filter));

            if (process.env.env != "DEV") {
                return cust_EntitlementBenefitPlanMain.execute({
                    destinationName: process.env.apiDest,
                    jwt: retrieveJwt(req)
                });
            } else {
                return cust_EntitlementBenefitPlanMain.execute({
                    destinationName: process.env.apiDestBasic,
                });
            }
        }

=========================================================================
The objects in console logs are following : 
{"andFilters":[{"andFilters":[],"orFilters":[{"field":"externalCode","operator":"eq","value":"70000001","edmType":"Edm.String","_fieldName":"externalCode"},{"field":"externalCode","operator":"eq","value":"70000002","edmType":"Edm.String","_fieldName":"externalCode"}]}],"orFilters":[]}


What I notice is that the way it construct by the core method have an additional [ ] which caused the filter not recognizable .
(left) - refers to existing code, (right) - new method using dynamic. 

![image](https://user-images.githubusercontent.com/66316812/92080620-6e816b80-edf4-11ea-9aa8-c834df7cc262.png)

**Comment by FrankEssenberger** [comment]
Yes, the double `[[` are not correct. Since we use mainly typescript we do not see such issues, because I get a compiler error if I do not use the spread `...` before inserting the error but this lead to the `TypeError: Found non-callable @@iterator` error. I will try to reproduce the issue and really execute the request.

**Comment by FrankEssenberger** [comment]
Can you add an `apply` to the filter function like this: `core.or.apply(void 0, filters)`. This was the result when I compiled my working TS example to JS. When I removed the `apply` I also got the double brackets. This is super ugly and I will create a ticket that we also have a clean API if you use JavaScript.

**Comment by FrankEssenberger** [comment]
I also tried the `...` in plain JS and this also works: `core.and(...filters)`. So perhaps you can give it one more try, because the `...` would be acceptable since you also need it in TS. I also looked at your snipped more closely:
```
const Filters = [Cust_PtfMain.CUST_CLAIM_STATUS.notEquals("Rejectd"), Cust_PtfMain.CUST_CLAIM_STATUS.notEquals("Pending")];

cust_PtfMainRequestBuilder.filter(or(...Filter));
```
And is there perhaps just a **s** missing: `const Filter**s** = ...` and then `cust_PtfMainRequestBuilder.filter(or(...Filter));`.

**Comment by phangkw** [comment]
Hi Frank, 

    The 2nd method works for me. Thank you very much and i think for now we can close this request as there is alternative workaround for now. Thanks !

**Comment by FrankEssenberger** [comment]
Hi @phangkw,

just a small update. We added support for array and variable arguments in most of the methods now. So once the content of this [PR](https://github.com/SAP/cloud-sdk-js/pull/651) is merged both ways i.e.:
```
and([filter1,filter2]) //should work now also
and(filter1,filter2) //initial wat
```

I hope we did not miss a relevant method.

Best
Frank
