### ISSUE TITLE
How to Filter On Null

### ISSUE THREAD

**Issue by SpaceCondor** [SAP/cloud-sdk#425]
### Discussed in https://github.com/SAP/cloud-sdk/discussions/424

<div type='discussions-op-text'>

<sup>Originally posted by **SpaceCondor** August 17, 2021</sup>
Is it possible to filter on a value being 'null'? I am trying to filter on a particular String being `null`.

For example:

`.filter(Order.COMMENTS.equalTo(null))`</div>

**Comment by cschubertcs** [comment]
Hi @SpaceCondor,

in the OData client of the Cloud SDK it's possible to create such a filter the following way:
```java
ValueBoolean filterFunction = FieldReference.of(BusinessPartner.FIRST_NAME.getFieldName()).equalTo(Expressions.Operand.NULL)
```

If you are using our OData V2 VDM you can then also consumer that filter the following way:
```java
new DefaultBusinessPartnerService()
            .getAllBusinessPartner()
            .filter(new UncheckedFilterExpression<>(filterFunction));
```

This is, however, only a workaround and will be improved on in the future.

For our OData V4 VDM there is no such workaround possible at the moment.
Also that is a thing we want to improve in the future.

If that already answers your question, feel free to close the issue, or let me know what I missed.

Greetings
Chris

**Comment by SpaceCondor** [comment]
Thank you! Unfortunately we are using V4 so that workaround won't work. Glad to know it is on your radar!

**Comment by newtork** [comment]
Is "COMMENTS" a `1:n` navigation property? Have you checked whether this filter expression works for the specific OData service?
Is this considered OData V2 or V4? For the latter, there's the [`Collection#length`](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_length) filter method, but some OData services may not support this filter expression.

**Comment by newtork** [comment]
@SpaceCondor , my suggestion would look like the following - have you tried...?
```java
FilterableBoolean<Order> noCommentsFilter = Order.COMMENTS.length().equalTo(0);
```

Alternatively, if you want to **enforce** the `null` comparison, that would be a bit tedious with today's public API on OData V4 VDM:
```java
FieldUntyped fieldUntyped = FieldReference.of(Order.COMMENTS.getFieldName());
ValueBoolean.Expression fieldExpression = (ValueBoolean.Expression) fieldUntyped.equalTo((Object) null);
FilterableBoolean<Order> noCommentsFilter = new FilterableBoolean.Expression<>(fieldExpression, Order.class);
```

Or another potential solution is to use our [OData Generic Client](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client#building-queries) for OData experts, but it may not take advantage of your generated OData API.

**Comment by SpaceCondor** [comment]
Hey @newtork, thanks for the suggestion! I actually had already tried that, but wasn't successful.

In this example, COMMENTS is a string, not a collection. I will play around with the generic client to see if I can get something workable in the meantime.

**Comment by newtork** [comment]
As of [`3.53.0`](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java#3530---september-13-2021) we support the following helper filter operators:

- `Entity.FIELD_NAME.equalToNull()` - OData V4 VDM / Generic OData Client
- `Entity.FIELD_NAME.notEqualToNull()` - OData V4 VDM / Generic OData Client
- `Entity.FIELD_NAME.eqNull()` - OData V2 VDM
- `Entity.FIELD_NAME.neNull()` - OData V2 VDM
