### ISSUE TITLE
Currency Conversion - Issues with building docu locally

### ISSUE THREAD

**Issue by rassumfrassum** [SAP/cloud-sdk#465]
I followed the steps described here to clone the SDK documentation. I was able to access the files and create a PR. However, ever since I have signed the CLA, I am unable to build the documentation locally by using npm install and npm start,

**Important information:**
Here's the code for npm install:

```
C:\Users\I333344\git\cloud-sdk>npm install
npm WARN @docusaurus/plugin-debug@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/plugin-google-analytics@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/plugin-google-gtag@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/plugin-sitemap@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/preset-classic@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/theme-classic@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/theme-search-algolia@2.0.0-alpha.61 requires a peer of @docusaurus/core@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @docusaurus/theme-search-algolia@2.0.0-alpha.61 requires a peer of @docusaurus/utils@2.0.0-alpha.60 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2021 packages in 16.664s

165 packages are looking for funding
run npm fund for details

found 0 vulnerabilities
```

When I do `npm start`, I get some 78 rejection ids.

**Impact / Priority**
It isn't critical since I can see the file changes on my PR but I would like to see an actual preview since there is some docusaurus formatting as well, which I want to check for correctness.

**Affected development phase:** Release

**Impact:** Impaired

**Timeline:
[Local Host Build.txt](https://github.com/SAP/cloud-sdk/files/5194980/Local.Host.Build.txt)
** GoLive ASAP

**Project Details**
Currency Conversion Library on Cloud SDK. The file in which the content was to be added was already created for us. We only edited the relevant file.

**Comment by rassumfrassum** [comment]
Update: Now the build is successful (after a system restart!) but the sub-pages are not loading. 
```
C:\Users\I333344\git\cloud-sdk>npm start

> sap-cloud-sdk-documentation@0.1.0 start C:\Users\I333344\git\cloud-sdk
> docusaurus start

Starting the development server...

√ Client
  Compiled successfully in 18.94s

i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from /cloud-sdk/
i ｢wds｣: Content not from webpack is served from C:\Users\I333344\git\cloud-sdk
i ｢wds｣: 404s will fallback to /index.html

√ Client
  Compiled successfully in 223.52ms
```

**Comment by newtork** [comment]
Does the problem exist only for new "sub-pages" or for all "sub-pages"?
Does the problem exist when not changing anything, i.e. working on master branch?

**Comment by MatKuhr** [comment]
Hi @rassumfrassum, typically such problems occur if there is a mistake in the sidebar.js. I'd recommend double checking any changes you may have made. Does it work for you if you try to run what is currently live on the `documentation` branch?

**Comment by rassumfrassum** [comment]
> Does the problem exist only for new "sub-pages" or for all "sub-pages"? Maybe a screenshot of observed behavior would help(?)
All sub-pages. I am not sure what you'd like to see a screenshot of because it is a blank page where nothing loads.
![image](https://user-images.githubusercontent.com/37209163/92878336-a22e4800-f429-11ea-8016-d91b0239140c.png)

> Does the problem exist when not changing anything, i.e. working on base branch (`documentation`)?
Yes, it exists even then.

**Comment by rassumfrassum** [comment]
> Hi @rassumfrassum, typically such problems occur if there is a mistake in the sidebar.js. I'd recommend double checking any changes you may have made. Does it work for you if you try to run what is currently live on the `documentation` branch?

I have only uncommented the Currency Conversion portion from the sidebar.js as advised. I haven't made any other changes. Should I re-comment and check?

**Comment by MatKuhr** [comment]
> Should I re-comment and check?

Yes, the commented out parts are not necessarily correct but rather only placeholders for future stuff. But if that was the cause you should also see errors in the log output where your `npm start` is running.

**Comment by MatKuhr** [comment]
You can also check out the (somehow hidden) getting started guide: https://sap.github.io/cloud-sdk/docs/dzen/getting-started/

**Comment by rassumfrassum** [comment]
> Yes, the commented out parts are not necessarily correct but rather only placeholders for future stuff. But if that was the cause you should also see errors in the log output where your `npm start` is running.
I only see warnings when I run npm start. No errors. 

>You can also check out the (somehow hidden) getting started guide: https://sap.github.io/cloud-sdk/docs/dzen/getting-started/
Yes, I followed the steps from here.

**Comment by rassumfrassum** [comment]
I cloned the original repo and was able to run the build locally. I have submitted my changes in a new PR directly through GitHub. Closing this.
