### ISSUE TITLE
Batch request error when response is processed

### ISSUE THREAD

**Issue by pepejuarez** [SAP/cloud-sdk#480]
## Batch request error when response is processed

When the response of a batch request is processed an error is raised. 
The content-type response header is received in lowercase, but we have seen that in the ODataRequestResultMultipartGeneric class the header name is searched using the string "Content-Type". Then the header is not found and it causes that the response can't be processed.

Important information:
Source code:
`BatchResponse resultBatch = reqBuilder.execute(odataSession.getDestination());
      for (GetAllRequestBuilder<T> queryBuilder : reqBuilderArray) {
        List<T> result = resultBatch.getReadResult(queryBuilder);
        if (returnList == null) {
          returnList = result;
        } else {
          returnList.addAll(result);
        }
      }
    }`
- Expected outcome: Response of the batch request
- Actual outcome: Error:
     2021-09-28 13:50:26.356  WARN 4112 --- [  XNIO-1 task-1] .o.c.r.ODataRequestResultMultipartParser : Illegal value in HTTP header "Content-Type" of OData batch response.
2021-09-28 13:50:26.428 ERROR 4112 --- [  XNIO-1 task-1] .o.c.r.ODataRequestResultMultipartParser : A boundary delimiter cannot be resolved from OData batch response header.

Maven dependency:
 <dependency>
                <groupId>com.sap.cloud.sdk.datamodel</groupId>
                <artifactId>odata-v4-core</artifactId>
                <version>3.52.0</version>
            </dependency>

![image](https://user-images.githubusercontent.com/13154812/135083004-164f433a-1187-44b8-a3d8-bdbb774d5416.png)

**Comment by newtork** [comment]
Hi @pepejuarez,

Please update to at least SAP Cloud SDK [3.53.0](https://sap.github.io/cloud-sdk/docs/java/release-notes-sap-cloud-sdk-for-java#3530---september-13-2021). We fixed the issue.

Kind regards

**Comment by newtork** [comment]
I'm closing the issue. Please let me know in case something is still failing.
