### ISSUE TITLE
Batch Response Headers

### ISSUE THREAD

**Issue by SpaceCondor** [SAP/cloud-sdk#483]
We are working with the SAP Business One Service Layer. One of the options to improve performance when adding documents is to add a `Preference` header requesting to `return-no-content` This overrides the basic behavior of returning the added document and instead returns a response with a header pointing to the location of the new document.

Example Request:

```
[Wed Sep 29 16:23:06 2021] [172.16.1.10] [pid=3684] [Request] "POST /b1s/v2/Orders HTTP/1.1"
Prefer:return-no-content
Accept:application/json
COOKIE:**************************************************************
Content-Type:application/json
Content-Length:695
Host:****************************
Connection:Keep-Alive
User-Agent:Apache-HttpClient/4.5.13 (Java/16.0.1)
Accept-Encoding:gzip,deflate
X-Forwarded-Proto:https
```

Response:

`[Wed Sep 29 16:23:06 2021] [172.16.1.10] [pid=3684] [Response] "POST /b1s/v2/Orders HTTP/1.1"
Status Code:[204 No Content]
Date:Wed, 29 Sep 2021 16:23:06 GMT
Server:Apache
OData-Version:4.0
Location:https://example.com:50000/b1s/v2/Orders(369453)
Preference-Applied:return-no-content
`

When doing this in single operation mode it works fine, I can simply get the response header like so:

```
// build OData Request
var addDocumentRequest = svcl.withServicePath(....)
		.createOrders(orderDocument)
		.withHeader("Prefer", "return-no-content");

// Order insertion request

var locationString = addResponse.get().getResponseHeaders().get("Location").iterator().next();
```

But when doing it with a batch, it seems like the response header isn't parsing correctly.

Example response:

```
[Wed Sep 29 16:23:07 2021] [172.16.1.10] [pid=3684] [Response] "POST /b1s/v2/$batch HTTP/1.1"
Status Code:[200 OK]
Date:Wed, 29 Sep 2021 16:23:07 GMT
Server:Apache
OData-Version:4.0
Content-Length:583
Content-Type:multipart/mixed;boundary=batchresponse_vgVD6N0o-oqPH-UJWJ-n1cg-84GYKJ63DMrX

--batchresponse_vgVD6N0o-oqPH-UJWJ-n1cg-84GYKJ63DMrX
Content-Type: multipart/mixed; boundary=changesetresponse_vgVD6N0o-oqPH-UJWJ-n1cg-84GYKJ63DMrX

--changesetresponse_vgVD6N0o-oqPH-UJWJ-n1cg-84GYKJ63DMrX
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

HTTP/1.1 204 No Content
Location: https://example.com:50000/b1s/v2/DeliveryNotes(366573)
OData-Version: 4.0
Preference-Applied: return-no-content

--changesetresponse_vgVD6N0o-oqPH-UJWJ-n1cg-84GYKJ63DMrX--
--batchresponse_vgVD6N0o-oqPH-UJWJ-n1cg-84GYKJ63DMrX--
```

But accessing it seems to not work correctly:

```
var addResponse = batchResponses.get().getModificationResult(addRequest);
			
System.out.println(addResponse.getResponseHeaders());
```

Prints the following:

`{Content-ID=[1], Content-Transfer-Encoding=[binary], Content-Type=[application/http]}`

If this isn't an issue with the SDK and is, in fact, an issue with the SAP Service Layer response format, is there an easy way to extract the location response?

**Comment by SpaceCondor** [comment]
Also, this is using the latest v4 SDK (3.54.0).

**Comment by Johannes-Schneider** [comment]
Hi @SpaceCondor,

thank you for reaching out to us.
Unfortunately, your observation is correct: The Cloud SDK does not parse headers of the "wrapped" responses within an OData batch response. All it currently does is to look at the headers of the "outer" HTTP response.
So I fear there is no way of getting the `Location` header with our current API.

I will bring this topic to the team to get opinions on how we can proceed here best.
Could you maybe share some more details about your use-case? I'm especially interested why you would like the entities to be excluded from the response. Are you using some kind of fire-and-forget approach where you simply do not care about the entities afterwards?
Understanding your use-case can help us to increase the priority for this feature as other consumers might also be interested in something similar.

In the meanwhile, is it an option for you to perform your batch requests without the `Preference` header? That should then result in the entities being included in the responses so that you can access them conveniently as usual.

Thanks and best regards,
Johannes

**Comment by SpaceCondor** [comment]
@Johannes-Schneider Thank you for the response!

To give more context; The entities in the SAP B1 Service Layer are quite large, and including them in the response content can lead to significantly decreased performance. The SAP documentation specifically mentions this here:

```
Considering the fact that returning all the entity content on creating one entity may be not suitable for the high
performance demanding scenario, Service Layer provides a way to respond no content by specifying a special
header Prefer with the value return-no-content. For example:

POST /b1s/v1/Items HTTP/1.1
Prefer: return-no-content
```

While doing batch operations, this problem is exacerbated since we will receive the entity content for every entity created.

For our scenario, we aren't using the returned entity in any way aside from getting the entity key, which is contained in the `Location` header. While importing orders, for example, a 'fire and forget' approach is relatively common as we just need to know if the operation was successful and what the key of the inserted entity is.

**Comment by Johannes-Schneider** [comment]
Thank you for sharing more details about your use-case. I can totally see how such a feature would help to improve performance in scenarios like yours.

I've created a new item in our backlog with your feature request. Unfortunately, I cannot promise on any delivery timeline.

We will keep you updated in this issue.

Best regards,
Johannes

**Comment by newtork** [comment]
I assume it turned out working for you.
