### ISSUE TITLE
Add ability to customize payload of a PUT  batch request

### ISSUE THREAD

**Issue by KurtStauffer** [SAP/cloud-sdk#505]
This feature request is related to [this problem](https://stackoverflow.com/questions/66640427/unable-to-create-contact-with-additional-id) that I posted on StackOverflow back in March. While the workaround certainly works, it would be nice to avoid using the low-level API if possible.

The problem is that when using `replacingEntity()` it will deserialize ALL of the properties into the request payload, including the read-only properties. SAP doesn't like when these properties are included in a `PUT` request and will reject it with the following error:
```
Inline component is not defined or not allowed (HTTP PUT)
```

Here's an example of my request:
```
contactService
        .updateAdditionalIDs(additionalId)
        .replacingEntity()
        .withHeaders(defaultHeaders)
        .executeRequest(destination);

Part of the request output:

PUT AdditionalIDs(ContactAdditionalOrigin='EMAIL',ContactAdditionalID='<email_address>',ContactID='<contact_id>',ContactOrigin='<contact_origin>') HTTP/1.1
Sap-Cuan-SourceSystemId: my-source
Accept: application/json
Sap-Cuan-SourceSystemType: EXT
Content-Type: application/json
Sap-Cuan-RequestTimestamp: '2021-10-15T14:24:11.578'

{ContactOrigin:<contact_origin>,ContactID:<contact_id>,ContactAdditionalOrigin:EMAIL,ContactAdditionalID:<email_address>,ContactAdditionalIdUUID:null,ContactUUID:null,ContactAddlIDIsInvalid:null,MarketingAreas:[]}
```

According to the metadata for contacts (edmx), `ContactAdditionalIdUUID`, `ContactUUID` & `ContactAddlIDIsInvalid` are marked as read-only...
```
<EntityType Name="AdditionalID" sap:content-version="4">
  <Key>
      <PropertyRef Name="ContactOrigin"/>
      <PropertyRef Name="ContactID"/>
      <PropertyRef Name="ContactAdditionalOrigin"/>
      <PropertyRef Name="ContactAdditionalID"/>
  </Key>
  <Property Name="ContactOrigin" Type="Edm.String" Nullable="false" MaxLength="20" sap:unicode="false" sap:label="Origin of Contact"/>
  <Property Name="ContactID" Type="Edm.String" Nullable="false" MaxLength="255" sap:unicode="false" sap:label="External Contact ID"/>
  <Property Name="ContactAdditionalOrigin" Type="Edm.String" Nullable="false" MaxLength="20" sap:unicode="false" sap:label="Origin of Contact"/>
  <Property Name="ContactAdditionalID" Type="Edm.String" Nullable="false" MaxLength="255" sap:unicode="false" sap:label="External Contact ID"/>
  <Property Name="ContactAdditionalIdUUID" Type="Edm.Guid" sap:unicode="false" sap:label="Additional ID UUID" sap:creatable="false" sap:updatable="false"/>
  <Property Name="ContactUUID" Type="Edm.Guid" sap:unicode="false" sap:label="UUID" sap:creatable="false" sap:updatable="false"/>
  <Property Name="ContactAddlIDIsInvalid" Type="Edm.Boolean" sap:unicode="false" sap:label="Invalid" sap:creatable="false" sap:updatable="false"/>
  <NavigationProperty Name="MarketingAreas" Relationship="API_MKT_CONTACT_SRV.AdditionalIDMarketingArea" FromRole="FromRole_AdditionalIDMarketingArea" ToRole="ToRole_AdditionalIDMarketingArea"/>
</EntityType>
```

Ideally, it would be nice if read-only properties were not deserialized into a `PUT` payload, but maybe as an alternative would it be possible to allow the usage of `includingFields()` when using `replacingEntity()` so that more fine grained customization can be achieved at the higher API level? In fact, there are some cases (like with `AdditionalIDs`) where the payload needs to be empty `{}` on a `PUT` request, so passing no args to `includingFields()` could solve for that case as well.

Thank you for your consideration on this feature request and please let me know if you have any questions or would like additional info.

Cheers!

**Comment by KavithaSiva** [comment]
Hi @KurtStauffer ,

We have included a new API `excludingFields()` which while used with `replacingEntity()` can be used to exclude fields from the PUT request payload.

Usage example(with BusinessPartner VDM):
```java
service.updateBusinessPartner(partner)
    .replacingEntity()
    .excludingFields(BusinessPartner.BUSINESS_PARTNER_FULL_NAME)
    .executeRequest(destination);
```
This feature would be shipped with SAP Cloud SDK version `3.63.0`. I will let you know here when it is released and available.

Regards,
Kavitha

**Comment by KurtStauffer** [comment]
This is fantastic news! Thank you for taking the time to work on this!

Cheers!
Kurt

**Comment by newtork** [comment]
Hi @KurtStauffer,

Please try out version `3.63.0` does it work for you?

Kind regards
Alexander

**Comment by KurtStauffer** [comment]
Hey @newtork, 

I'd be happy to try it out, however, the latest version I can see is `3.62.0`.

**Comment by newtork** [comment]
Hi Kurt,
You are right. I mixed up the release dates: `3.63.0` will be available on _SAP Nexus_ by end of this week and on _Maven Central_ by next week.
Kind regards
Alexander

**Comment by KurtStauffer** [comment]
No worries at all, I'll keep my eyes open for it. Thanks @newtork!

**Comment by MatKuhr** [comment]
FYI: 3.63.0 is now available on Maven Central. I'll close this item, please re-open if something isn't working as expected.

**Comment by MatKuhr** [comment]
Thanks a lot for the feedback! 

Yeah, on OData V2 currently the navigation links are not treated as normal fields. But maybe we can extend the API to also allow excluding (and including) navigation properties. We'll let you know if we can do that, otherwise your solution should also be just fine 👍🏻

**Comment by jjtang1985** [comment]
API_MKT_CONTACT service of the Marketing Cloud is consumed
