### ISSUE TITLE
The manual OData call to C4C works fine, while same call via SDK doesn't

### ISSUE THREAD

**Issue by artemkovalyov** [SAP/cloud-sdk#508]
**Describe the bug**

Querying IndividualCustomers from C4C
To do this we tried out two variations:
    1. Querying the ODATA API directly using a lambda function in Kyma (see file get-indiv-customers.js). Using the $expand syntax it is possible to list all the current customer’s addresses, i.e. this works as expected (see file response-indiv-customers-native.json)
    2. Using the CloudSDK to query C4C. In this case the syntax is slightly different (see file get-indiv-customers-sdk.js). In this case we always get back an empty array of addresses, even if the IndividualCustomer has addresses in C4C (see file response-indiv-customers-sdk.json). We observe this behavior for all of the IndividualCustomer child entities we have tested.

Thanks for your help!

**To Reproduce**
Please note that to use the Cloud SDK Nazar has set up a node.js module which is installed as a dependency in the lambda function. The library he set up is available at https://github.com/PTA-Kyma/pta-kyma-c4-odata.git (to install: @nazarkulyk/pta-kyma-c4-odata)

**Expected behavior**
The call returns data with Expand

**Used Versions:**
We'll 

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information as it will be shown in the internet.

**Comment by FrankEssenberger** [comment]
I can not access the repo.

**Comment by FrankEssenberger** [comment]
or share the ` get-indiv-customers.js` and `get-indiv-customers-sdk.js`. In general the expand should work.

**Comment by FrankEssenberger** [comment]
I just made checked and we have a [test](https://github.com/SAP/cloud-sdk/blob/45af0f068c77976daae1eb7ab4297dfe47a3d063/test-packages/e2e-tests/test/TripPin/request-builder.spec.ts#L31-L40) for that against the  `https://services.odata.org/TripPinRESTierService` 
service. It is working as expected.

**Comment by artemkovalyov** [comment]
Yeah, I was also unable to access the repo @FrankEssenberger. I'm working on it and on repro scenario. Thanks for looking into this.

**Comment by FrankEssenberger** [comment]
I had a quick look at the issue and the good news is I can reproduce the bug against our sanbox system. The URL from the SDK is still correct and then the error appears in the deserializing of the JSON payload. We assume, that the elements in the 1:N [relation have the form](https://github.com/SAP/cloud-sdk/blob/45af0f068c77976daae1eb7ab4297dfe47a3d063/packages/core/src/odata/v2/extract-data-from-one-to-many-link.ts#L9): 
```
{
FirstName:Max,
INdicidualCustomerAddress:{
   data: [{}.{},...
   ]
}
```

For the S/4 OData Apis this is the case and I think it is also OData spec for v2 to have this wrapping in a `data` object. However, the C4C does not do that an directly puts the list of addresses. A quick should be easy. We try release a patch version as soon as possible. Thanks for pointing our attention to the issue.

In the mean time, if you want to use the SDK for connectivity you can always use the [untyped http client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/generic-http-client).

**Comment by artemkovalyov** [comment]
@FrankEssenberger , let's keep it open before the fix is released. Thanks for the investigation!

**Comment by pta-nmu** [comment]
Thanks for looking into this and I look forward to getting the patch
Nick

**Comment by FrankEssenberger** [comment]
@pta-nmu We created a [patch release 1.28.1](https://github.com/SAP/cloud-sdk/releases/tag/v1.28.2) which should solve the issue.

**Comment by marikaner** [comment]
I will go ahead and close this issue. Feel free to create a new one if you still encounter any issues.
