### ISSUE TITLE
Regd: Documentation for sap-cloud-sdk/generator for javascript

### ISSUE THREAD

**Issue by shankarigr** [SAP/cloud-sdk#54]
Hello,

It would be really helpful if you can help me with some help.sap.com documents/blogs/tutorials on sap-cloud-sdk/generator for javascript.

Thanks and Regards,
Shankari G R

**Comment by jjtang1985** [comment]
Hi Shankari,

thank you for approaching us.

In general, you can find the documentation [here](https://sap.github.io/cloud-sdk/) for all packages. For more specific, if you check the right side of the page, you can find a link to the page of the `@sap-cloud-sdk/generator`.

I guess you can find some general docs there.

If you have some specific questions, please feel free to share more details here.

Best regards,
Junjie

**Comment by artemkovalyov** [comment]
Hi, @shankarigr, we're planning a how-to on using the generator. I added it to the backlog. We'll update you after it's ready.

**Comment by shankarigr** [comment]
Hi,
Thanks for the update.
Regards,
Shankari G R

**Comment by marikaner** [comment]
Hey @shankarigr,

we just released documentation on the generator: https://sap.github.io/cloud-sdk/docs/js/features/odata/generator-js-sdk.
Let us know if you think anything is missing there or if you have any other feedback. I will close this issue for now.

**Comment by shankarigr** [comment]
Hi,

Thank you so much for the update.

Regards,
Shankari G R
