### ISSUE TITLE
OData $count operation

### ISSUE THREAD

**Issue by robypag** [SAP/cloud-sdk#56]
Hello there,
wouldn't be nice to implement the count() operation for VDM entities?
Although for server pagination this might not be required, the total count of entity values is very much useful in many other scenarios, especially in UIs that require table paging.

Best option will be to implement the count() method in the requestBuilder, so that it can be used as fluently as other API methods (top, skip, filter, etc).

As of now, the count can be easily obtained by shooting a separated http call for the required entity, and appending $count parameter to the call.

All the best,
Roberto.

**Comment by jjtang1985** [comment]
Hi Roberto,

thank you for your feedback.

I created a ticket for your feature request and will discuss it in the next refinement meeting.

I'll give you an update after that.

Best regards,
Junjie

**Comment by FrankEssenberger** [comment]
It took really long since we were focusing on the OData v4 support, but finally the basic count functionality is coming #481.

**Comment by marikaner** [comment]
@robypag I will go ahead and close this feature request as it was released in the last version. If you have feedback concerning the API feel free to share.
