### ISSUE TITLE
Javascript sdk Batch with filter

### ISSUE THREAD

**Issue by d-sooter** [SAP/cloud-sdk#568]
**Describe the bug**
I ran into issues while trying to pass filters to a batch 'GET' requests.
The sap system return Malformed syntax error

I already found the error it seems that the filters are getting parsed wrong in odata when passing the filter using the URL we have to add spaces between the commands 

ex:
?$filter=name eq 'myname'

however in batch the spaces need to be replaced by a plus sign. 
ex: 
?$filter=name+eq+'myname'

**To Reproduce**

The error should be very easy to reproduce just add a filter to a batch request

**Comment by marikaner** [comment]
Hey @d-sooter, thanks for reporting this. I'll fix it for the next version.

**Comment by d-sooter** [comment]
do you know when the next version will be released? 

kind regards 
David

**Comment by marikaner** [comment]
Probably today ;) but this is not promise.

**Comment by d-sooter** [comment]
awesome thank you.

**Comment by marikaner** [comment]
Hey @nazarkulyk,

Version 1.30.0 was released with a fix for this yesterday. Let us know if this is still an issue.
