### ISSUE TITLE
Failed request error message is not descriptive 

### ISSUE THREAD

**Issue by crazio** [SAP/cloud-sdk#625]
**Is your feature request related to a problem? Please describe.**
I use SAP Cloud SDK with combination of SAP CAP (not Typescript, but Javascript). More precisely, I use `@sap/cloud-sdk-vdm-planned-independent-requirement-service` module. So I try to create entity in external on-premise system in this kind of way (code is shorten a little bit for simplicity):
`const result = await PlannedIndepRqmt.requestBuilder().create(newEntity).execute(this.credentials);`
Also, this code spot is surrounded with `try - catch` to handle errors. Whenever I got error from external system I catch exception with two attributes: `message` and `stack` (like on screenshot from debugger below). If you check message attribute you will see that it is not descriptive enough (second screenshot): so from it I know that request has failed, but I don't know. Although if you check stack attribute there is real cause of error is hidden (last screenshot)

![image](https://user-images.githubusercontent.com/56916986/97188380-7f2ade00-17b4-11eb-9562-b1ace94c33f7.png)
![image](https://user-images.githubusercontent.com/56916986/97188498-9ec20680-17b4-11eb-8e80-05e24f019b7b.png)
![image](https://user-images.githubusercontent.com/56916986/97189714-f14ff280-17b5-11eb-9d25-b48d36bfe533.png)

**Describe the solution you'd like**
Probably I miss something (function, class, etc.), but I don't know how to get the real cause of issue from here. I don't think that getting string from stack and parse it to object is a good idea. I noticed, that if you use this create in `batch`, it will return you response where all the information for request is accessible, so now I can retrieve root error message. Can you, please, advice me how can I retrieve error message from external system or probably provide some additional functionality for this?

Thanks a lot!

**Comment by marikaner** [comment]
Hey @crazio, 

am I understanding correctly that this error is returned in the response of the request? And you are saying that you found it in the stack but it was hidden? Can you specify what you mean by "hidden"?

**Comment by crazio** [comment]
Hi @marikaner,

This error is the error that comes in response from on-premise system. In exception which is raised in my example we catch object which has 2 properties: message - string with text 'Create request failed!' and stack - the call stack string. In this call stack string we can notice the JSON on screenshot below where exact error from response can be found. I just described a little bit incorrectly: I meant that there is correct error in stack property, but I didn't expect to find it here, so that' why I said some kind 'hidden'
 
![image](https://user-images.githubusercontent.com/56916986/97257680-abcc0d80-1827-11eb-88c5-d06dd64b6ce0.png)

**Comment by marikaner** [comment]
Hey @crazio,

Ok, I understand that better now. So what is it that you are asking for? Do you need a different format of the error? If yes, what is the format you would expect?

**Comment by crazio** [comment]
Hi @marikaner,

I would say I just need to get access to original error message which came in response from on-premise system, probably in exception object there should also be some additional property like 'responseError' or 'rootCause' or something similar and this property will store the error object from response, so I can easily retrieve it and display for the end-user in my application

Thanks!

**Comment by marikaner** [comment]
Hey @crazio, 

what a coincidence, somebody else reported the same issue today #634. I will close this issue as those are duplicates, but feel free to watch the other issue. Let me know if you think it is not a duplicate.
