### ISSUE TITLE
Multi Tenancy with the Thread Context

### ISSUE THREAD

**Issue by blangero** [SAP/cloud-sdk#631]
Hi Experts,

I've ever get tenant and user info via TenantAccessor and PrincipalAccessor, but it's not that stable - by which I mean after a night it won't return any value anymore.

I think there must be something wrong how I use the library, as there's no sample application / detailed guide, I want to search help here:

1. I'm using this link as reference, as mentioned in the document 'RequestFilter' is used to get Thread Context. Then how should I enable such a filter? for now I add below segment in my web.xml:

```
<filter>
 <display-name>RequestAccessorFilter</display-name>
 <filter-name>RequestAccessorFilter</filter-name>
 <filter-class>com.sap.cloud.sdk.cloudplatform.servlet.RequestAccessorFilter</filter-class>
</filter>
<filter-mapping>
 <filter-name>RequestAccessorFilter</filter-name>
 <url-pattern>/*</url-pattern>
</filter-mapping>
```
and following dependency in my pom.xml:

```
<dependency>
    <groupId>com.sap.cloud.sdk.cloudplatform</groupId>
    <artifactId>servlet</artifactId>
</dependency>
```
is this enough for the filter to be enabled?

2. to get tenant and user information, I have code like below:

```
import com.sap.cloud.sdk.cloudplatform.tenant.TenantAccessor;
import com.sap.cloud.sdk.cloudplatform.security.principal.PrincipalAccessor;
import com.sap.cloud.sdk.cloudplatform.thread.ThreadContextAccessor;
...

PrintWriter out = response.getWriter();
response.setContentType("text/plain");
response.setCharacterEncoding("UTF-8");
out.print(Encode.forHtml(
"TenantAccessor: "+ TenantAccessor.getCurrentTenant().getTenantId()) + 
"; PrincipalAccessor: " + PrincipalAccessor.getCurrentPrincipal() + 
";ThreadContextAccessor: " + ThreadContextAccessor.getCurrentContext().toString());
...
```
with the following pom.xml:

```
<dependency>
 <groupId>com.sap.cloud.sdk.cloudplatform</groupId>
 <artifactId>tenant</artifactId>
</dependency>
<dependency>
 <groupId>com.sap.cloud.sdk.cloudplatform</groupId>
 <artifactId>security</artifactId>
</dependency>
```
just want to know am I including the right dependency? do I need to include dependency

```
tenant-scp-cf
security-scp-cf
```
or just
`scp-cf`
instead?

Kindly let me know if there're already some documents / sample code about this feature.

Thanks and regards,

Blan

**Comment by newtork** [comment]
(duplicate https://answers.sap.com/questions/13172806/index.html)

**Comment by artemkovalyov** [comment]
Hi @blangero 

Let's move our discussion on this issue to our internal repository for Java. See my email. That's the default channel for Java for now.

Best,
Artem
