### ISSUE TITLE
Basic Authentication against S/4Hana not successful because of an additional x509 client certificate in request

### ISSUE THREAD

**Issue by matthiasbuchholz** [SAP/cloud-sdk#662]
Hi,

we are using the cloudsdk java in version 3.53 and try to call via the cloud connector our s/4hana on-premise
system.
We created a destination service and a connectivity service and have two exposed system connections from
the cloud connector. DESTINATION_A is setup using principal propagation, DESTINATION_B is setup using
basic authentication. In DESTINATION_B we have provided a technical user and password of S/4HANA and
also maintained the sap-client parameter.

As we have to be able to use both scenarios (technical user + principal propagation) we had set our profile
parameter in the s4hana 2020 fsps01 system to: icm/HTTPS/verify_client = 1

These destination_A and DESTINATION_B route are able to successfully authenticate from a second custom
service which is an unmanaged approuter (build via the MTA template in BAS). We are able to fetch data
from the S/4HANA system.
We need to achieve the same from a java app that is build using the cloudsdk 3.53.

We enabled the SEC_TRACE_ANALYZER trace with level 3 and saw that in case of DESTINATION_B being used from within cloudsdk's app, it is getting an 401 error unauthorized trying to authenticate the user. 
In the trace we see that the request is both including in the basic header authentication as well as it does contain a client x.509 certificate.

Also as the approuter route using exactly the same destination DESTINATION_B and connectivity service does work with basic.
Thus our assumption is that the issue is with the implementation of the standard cloudsdk java framework. As
the same route is able to get through and authenticated via the approuter

Please look into why the cloudsdk is injecting a x.509 certifcate though the destination is set to basic.

Best regards

Matthias

xs-app.json of app router is:
```
{
"authenticationMethod": "route",
"routes": [
{
"source": "/destnopp/(.*)$",
"destination": "CS_ERP_S1X_NOPP",
"authenticationType": "none",
"target": "/$1",
"csrfProtection": false
}]
}
```

DESTINATION_B is defined as:
```
{
"Name": "CS_ERP_S1X_NOPP",
"Type": "HTTP",
"URL": "XXXXXXXX",
"Authentication": "BasicAuthentication",
"ProxyType": "OnPremise",
"Description": "Destination for Technical User",
"User": "XXXXXXXX",
"CloudConnectorLocationId": "XXX",
"sap-client": "XXX"
}
```

Java code to obtain destination:
```
public HttpDestination getS4DestinationNoPP() {
        return DestinationAccessor.getDestination(nameOfDestinationS4NoPP).asHttp().decorate(DefaultErpHttpDestination::new);
    }
```

Java code to execute request:
```
List<ProjectionRootForDefensiveDec> defensiveDecList = s4ServiceForDefensiveControl.getAllXBAY0xPV_DEFENSIVE()
                .filter(ProjectionRootForDefensiveDec.DOCUMENT_NUMBER.eq(notaFiscalId))
                .executeRequest(destinations.getS4DestinationNoPP());
```

Error Log indicates 401:
`... "logger":"com.sap.cloud.sdk.cloudplatform.servlet.RequestAccessorFilter","thread":"http-nio-8080-exec-3","level":"WARN","categories":[],"msg":"Unexpected servlet filter exception: org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.sap.cloud.sdk.datamodel.odata.client.exception.ODataResponseException: The HTTP response code (401) indicates an error.","stacktrace":["com.sap.cloud.sdk.cloudplatform.thread.exception.ThreadContextExecutionException: org.springframework.web.util.NestedServletException: Request processing failed; nested ....`

**Comment by newtork** [comment]
Hello Matthias,

Please consider the following Java code:
```java
Destination destination = DestinationAccessor.getDestination(nameOfDestinationS4NoPP);
```

Is it possible for you to check what the following snippet returns?
```java
Option<Object> certificates = destination.get("certificates");
```

Furthermore, can you please attach the full error log entry (including the full stack trace).

Kind regards,
Alexander

**Comment by newtork** [comment]
Hi @matthiasbuchholz,

We'll continue issue discussion internally in _Service Now_.

Kind regards
Alexander
