### ISSUE TITLE
VDM for SOAP APIs in Javascript SDK

### ISSUE THREAD

**Issue by I304296** [SAP/cloud-sdk#70]
There are still plenty of S/4 HANA APIs that uses SOAP. It's very common to use them in real projects. However I dont find on how to create a VDM for a SOAP API (S/4) on a Javascript SDK. Can you please let me know how this can be done? if this is missing then please let me know if this feature is in roadmap?

**Comment by artemkovalyov** [comment]
Hi @I304296 

As of now JS SDK doesn't support SOAP. We still have it in Java SDK as it's a more frequent use-case there. Can you please let us know more about your use-case and why OData or REST (OpenAPI) wouldn't work? To what extend do you plan to use it?

cc @frank-essenberger  @marikaner 

Best,
Artem

**Comment by FrankEssenberger** [comment]
@FrankEssenberger

**Comment by artemkovalyov** [comment]
Hi @I304296,

I think this [project](https://github.com/SAP/node-rfc) might work for you instead or together with the Cloud SDK to make RFC calls from JS. It's by SAP and seems mature, active, and well-maintained. You can also consider our Java SDK if the language is not so important. 

I'll be closing this issue as we can't provide much more on this topic at the moment. Feel free to re-open this one or create a new issue if you have any other SDK related questions :)
