### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by git-ashish** [SAP/cloud-sdk#710]
Hello,

The search feature on the [SAP Cloud SDK documentation](https://sap.github.io/cloud-sdk/docs/overview/overview-cloud-sdk) is broken.

![image](https://user-images.githubusercontent.com/2697421/155935456-2713520c-cd81-47f8-893a-728a4d099988.png)

Thanks.

**Comment by Johannes-Schneider** [comment]
Hi @git-ashish,

thanks for bringing this issue to our attention.

We are working on a fix.

Best regards,
Johannes

**Comment by Johannes-Schneider** [comment]
This issue has been fixed. Sorry for the long delay!
