### ISSUE TITLE
Token forwarding in Kyma/CF environemnt

### ISSUE THREAD

**Issue by mvmanov** [SAP/cloud-sdk#817]
Hi,
 I am trying to forward the original token received by an application to a second application bound to the same XSUAA instance. I successfuly achieve that when I use a destination specified via env variable like this

`[{
	"name": "envapp2app",
	"url": "https://url...",
	"authentication": "TokenForwarding"
}]`

Though I am not able to achieve the same when configuring a destination via the BTP cockpit where I cannot specify authn type
"TokenForwarding".

Best regards,
Milen

**Comment by newtork** [comment]
Please try the following workaround until we have a proper solution:
```java
HttpDestination httpDestination = DestinationAccessor.getDestination("abc").asHttp();

// workaround
if( dest.get("forwardAuthToken").contains("true") ) {
    httpDestination = DefaultHttpDestination.builder(httpDestination).authenticationType(AuthenticationType.TOKEN_FORWARDING).build();
}
```

**Comment by mvmanov** [comment]
Hi,
 Thanks for the quick response. When I try the workaround I get the following exception

java.util.NoSuchElementException: No value present
	at io.vavr.control.Option$None.get(Option.java:526)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination.lambda$builder$3(DefaultHttpDestination.java:197)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1082)
	at com.sap.cloud.sdk.cloudplatform.connectivity.DefaultHttpDestination.builder(DefaultHttpDestination.java:196)


when debugging I see these are two properties that I do not have as configuration in the destination
authTokens and certificates, but the builder iterates over them.

Best Regards,
Milen

**Comment by newtork** [comment]
Hi Milen,

looks like we encountered an unrelated bug here. I'll file a fix soon.
In the meantime, please try the following instead:

```java
HttpDestination httpDestination = DestinationAccessor.getDestination("abc").asHttp();

// workaround
if( httpDestination.get("forwardAuthToken").contains("true") ) {
  String name = httpDestination.get("Name", String.class).get();
  URI uri = httpDestination.getUri();
  httpDestination  = ScpCfHttpDestination.builder(name, uri).authenticationType(AuthenticationType.TOKEN_FORWARDING).build();
}
```

Sorry for the inconvenience.

Kind regards
Alexander

**Comment by mvmanov** [comment]
Responding late since I was few days off, but just to confirm that with that approach everything works. Thanks for the support and for the SDK, I really enjoy using it and it accelarates my works.
