### ISSUE TITLE
SAP Cloud SDK OData client does support Versioning

### ISSUE THREAD

**Issue by mak08** [SAP/cloud-sdk#916]
## SAP Cloud SDK OData v4 client does support Versioning

OData services evolve, but in the OP world, customers may stick with older versions. 
Our Cloud App will be required to support multiple versions of an OData service in the very near future.

While we can work around the issue by generating and using multiple independent clients, having versioning support on the SDK would be extremely helpful. Without it, many applications may be forced to "re-invent the wheel".

### Impact / Priority

Impact: Inconvenience / duplicated development effort across applications

Timeline: needed immediately, but we will be happy to discard our (not yet implemented) home-grown solution any time.

## Project Details

[SAP Variant Configuration and Pricing](https://github.wdf.sap.corp/CPServices)

---

**Comment by Johannes-Schneider** [comment]
For transparency: This issue has been handled via E-Mail communication.

Currently, the best approach to tackle this kind of scenario is to generate the typed clients for the OData services **yourself**.
You can use the [OData generator Maven plugin](https://sap.github.io/cloud-sdk/docs/java/features/odata/generate-typed-odata-v2-and-v4-client-for-java#using-the-odata-generator-maven-plugin) to generate multiple services (or different versions of the same service) using different package names to ensure proper separation.

**Comment by newtork** [comment]
Closed due to inactivity (via mail)
