### ISSUE TITLE
Documentation for Destination from Service Binding

### ISSUE THREAD

**Issue by martindonadio** [SAP/cloud-sdk#930]
Hi, 

In this section https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#service-binding-environment-variables you mention that out-of-the box there are 5 (6 listed) services types that can be used to generate a Destination just from the service binding information (in VCAP_SERVICES env variable). Could you please share an example? How should be used? How to tell the SDK to look for the VCAP_SERVICES instead of looking for the destination service. 

Just below, we find this statement, "If you need a destination for a different service, create a custom serviceBindingTransformFn and pass it with destinationFetchOptions or consider creating a [feature request](https://github.com/SAP/cloud-sdk-js/issues/new?assignees=&labels=feature+request&template=feature_request.md&title=). Contributions providing transform functions are highly welcome" 

Same case here, could you please provide an example of this ? 

Thank you

Best regards,
Martin

**Comment by jjtang1985** [comment]
Hi @martindonadio ,

Thanks for reaching out here.
Actually we are aware the missing documentation and I linked the backlog ticket, which will be handled soon.

To give you a short answer before the documentation, you can check our unit [here](https://github.com/SAP/cloud-sdk-js/blob/main/packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts).
- [create a destination from a saws registry](https://github.com/SAP/cloud-sdk-js/blob/main/packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts#L78)
- [use custom transformation function](https://github.com/SAP/cloud-sdk-js/blob/main/packages/connectivity/src/scp-cf/destination/destination-from-vcap.spec.ts#L137)

Please note, we use an internal function `destinationForServiceBinding` in all the tests, which should be replaced by `getDestination` as the public API.

**Comment by jjtang1985** [comment]
Hi @martindonadio ,

Please check the new section [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#service-binding-environment-variables).
