### ISSUE TITLE
Documentation for BTP Kyma Runtime

### ISSUE THREAD

**Issue by mperumalswamy** [SAP/cloud-sdk#932]
Hi,

As mentioned in this section, https://sap.github.io/cloud-sdk/docs/java/environments/sap-btp-kyma-environment#bind-sap-btp-services-to-the-application, It fails to bind any services. It doesn't have the latest Kyma instance screenshot or with deprecated yml examples.

Could you please update it or add external links to SAP Help page if it exists?

Best regards,
Madhu

**Comment by newtork** [comment]
Hi Madhu,

Thank you for your interest in Cloud SDK on the Kyma runtime! We are aware of incompatibilities that recently started to occur. Unfortunately we missed to transparently update our documentation for this problem. Hence I created a PR to add a temporary note until we fixed it.

I hope we can have a proper solution in the next two weeks. In case you require a more timely commitment, please let me know.

I'm not aware of external links beyond [the official documentation](https://kyma-project.io/docs/kyma/latest/01-overview/).

Kind regards
Alexander

**Comment by mperumalswamy** [comment]
Hi Alexander,

Ok then I can also try to update and send you PR for it.

Best regards,
Madhu

**Comment by mperumalswamy** [comment]
Hi Alexander,

Ok then I can also try to update and send you PR for it.

Best regards,
Madhu
