### ISSUE TITLE
inconsisten definition in cache islosltion UserTenant or TenantUser 

### ISSUE THREAD

**Issue by GoWale** [SAP/cloud-sdk#935]
HI,

i hope this ist the right way to point it out.
Just getting started with BTP and i had a look at the cloud sdk docs.

on: https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-cache-isolation

I got confused because the isolation values looked mixed up.
first the name is: **"UserTenant**: The destination is ..."
then it is called "Isolation is **TenantUser** and values"

i think this is just a typo.

regards
Norbert

**Comment by FrankEssenberger** [comment]
Hi @GoWale,

yes this is the right place here for remarks on the documentation. Thanks for bringing this to our attention.
The correct name is [TenantUser](https://github.com/SAP/cloud-sdk-js/blob/3bff42e1aa498baec330a11c5d3af9e1122cbae2/packages/connectivity/src/scp-cf/destination/destination-cache.ts#L18) - you are right it is a typo.

PR: https://github.com/SAP/cloud-sdk/pull/944

Best
Frank
