### ISSUE TITLE
oData request with NavigationProperty

### ISSUE THREAD

**Issue by anco24** [SAP/cloud-sdk#953]
Hi,

I want to get oData from onplemise SAP by using sap-cloud-sdk.

I can execute the following request in java.
http://<hostname>/sap/odata/sap/<servicename>/<entity>

However, I don't know how to execute the following request.
http://<hostname>/sap/odata/sap/<servicename>/<entity>(startDate=datetime'2022-01-01T00:00:00',endDate=datetime'2022-06-10T00:00:00')/AAA
How do I implement this request by sap-cloud-sdk?

This VDM class has following method.
.getAll<entityname>Parameters()
.get<entityname>ParametersByKey(Date Date1, Date Date2)
.get<entityname>ByKey(Date date1,Date date2,String id)

I referred to the URL below.
https://sap.github.io/cloud-sdk/docs/java/features/odata/use-typed-odata-v2-client-in-sap-cloud-sdk-for-java#navigation-properties

I want to use this code, but .asChildOf() method is not found in the VDM class.
```
BusinessPartner businessPartnerById = BusinessPartner.builder().businessPartner("123").build();
BusinessPartnerAddress addressItem = BusinessPartnerAddress.builder().country("DE").build();

service.createBusinessPartnerAddress( addressItem )
    .asChildOf( businessPartnerById, BusinessPartner.TO_BUSINESS_PARTNER_ADDRESS )
    .execute( destination );
```

Thanks and best regards,
anco

**Comment by Johannes-Schneider** [comment]
Hi @anco24,

thanks for reaching out to us.

I just tried our sample code and everything seems to be working fine:

```java
//import com.sap.cloud.sdk.cloudplatform.connectivity.DestinationAccessor;
//import com.sap.cloud.sdk.cloudplatform.connectivity.HttpDestination;
//import com.sap.cloud.sdk.s4hana.onpremise.datamodel.odata.namespaces.businesspartner.BusinessPartner;
//import com.sap.cloud.sdk.s4hana.onpremise.datamodel.odata.namespaces.businesspartner.BusinessPartnerAddress;
//import com.sap.cloud.sdk.s4hana.onpremise.datamodel.odata.services.DefaultBusinessPartnerService;

HttpDestination destination = DestinationAccessor.getDestination("myDestination").asHttp();
BusinessPartner businessPartnerById = BusinessPartner.builder().businessPartner("123").build();
BusinessPartnerAddress addressItem = BusinessPartnerAddress.builder().country("DE").build();
DefaultBusinessPartnerService service = new DefaultBusinessPartnerService();

service
    .createBusinessPartnerAddress(addressItem)
    .asChildOf(businessPartnerById, BusinessPartner.TO_BUSINESS_PARTNER_ADDRESS)
    .executeRequest(destination);
```

Could you please check whether you are using some different imports? Since S/4HANA Services exist in different editions (i.e. Cloud vs. On-Premise) it is easy to mix up imports from different packages as the class names are the exact same.

In any case, please let me know whether the above example works as expected for you.

Best regards,
Johannes
