### ISSUE TITLE
CAP Service requests will returns 400 If I use FLP morethan 30 Minutes continuously 

### ISSUE THREAD

**Issue by sureshbabugonuguntla** [SAP/cloud-sdk#982]
## Issue Description

When we use the FLP more than 30 minutes all the requests will return 400, user has to logout or clear browser cache or run in incognito window to resolve the issue.

Important information:

- Your code 
- Expected outcome
- Actual outcome
- Steps attempted to resolve the issue 
  - What happens when a request is performed directly via an HTTP client tool such as Postman? Metadata always success
- Potentially missing information (open questions you might have)
- I can see request method "HEAD" are getting failed with 403 and for subsequent calls we can't see "If-Nonf-Match" header

### Impact / Priority

User has to logout and login again

Affected development phase: Release

Impact: Inconvenience

Timeline:  Go-Live is in 2 weeks.

## Error Message

```
"Could not get HttpClient cache.","stacktrace":["com.sap.cloud.sdk.cloudplatform.thread.exception.ThreadContextAccessException: No ThreadContext available for thread id=73."
```

 

## Project Details
 
- 

@sap/cds | "^5.7.5"
-- | --
@sap/cds-compiler | "2.12.0"
@sap/cds-dk | "^4.7.2"

- Link to GitHub repository: https://github.tools.sap/AssetPerformanceManagement/assetbase/tree/master/indicators-srv
- Project type, for example:
  - [ ] CAP Project
  - [ ] SAP Cloud SDK Maven Archetype
- Platform:
  - [ ] Cloud Foundry

---

**Comment by MatKuhr** [comment]
Hi, it seems like you are using CAP. Please [open an issue here](https://github.tools.sap/cap/issues) instead. Also, please give a more extensive description in there. From what you describe above it is unclear which components are involved and which one is throwing what error at what point in the communication flow. But so far I don't see a relation to the SAP Cloud SDK. The exception you copied is not necessarily critical, depending on your use case (in more recent SDK versions it was moved to debug logs)
